### ISSUE TITLE
In the API Browser, MicrosoftEextensions should be documented under .NET Core too

### ISSUE THREAD

**Issue by docs-product** [MicrosoftDocs/feedback#101]
The Microsoft.Extensions libraries appear only under ASP.NET Core although they can be used by any .NET Project. This is confusing developers, as shown in this SO question:

https://stackoverflow.com/questions/46914981/why-is-microsoft-extensions-documented-under-asp-net

Please display the Microsoft.Extensions libraries under `.NET Core` as well as `ASP.NET Core`

----------
⚠ Idea migrated from UserVoice

**Created By:** Panagiotis Kanavos
**Created On:** 2017/10/24 16:04:02 +0000
**Votes at Migration:** 3
**Supporters at Migration:** 3

**Comment by MV10** [comment]
This is a problem throughout the Microsoft documentation. The only how-to articles for things like DI and Configuration are completely focused on web apps. It isn't too difficult to figure out how to use these features in other scenarios but it's initially very misleading to anyone new to Core.

**Comment by dend** [comment]
@mairaw @BillWagner @rpetrusha what are your thoughts on this? What is the correct location for the documentation in this case?

**Comment by mairaw** [comment]
Tagging @Rick-Anderson and @natemcmaster for this

My understanding is that those APIs come from a NuGet package (https://www.nuget.org/packages/Microsoft.Extensions.Configuration/) developed by the ASP.NET team. 
The .NET team has chosen to only add API docs that are part of the shared framework and not extension packages as the correct support for NuGet packages is not implemented yet. I don't know what has been the process for the ASP.NET Core docs.

**Comment by Rick-Anderson** [comment]
@danroth27  please review this API question

**Comment by danroth27** [comment]
The Microsoft.Extensions.* packages are included as part of the ASP.NET Core shared framework, so I think it makes sense to document them with ASP.NET Core. These packages also target .NET Standard and can be used outside of ASP.NET Core (on .NET Core, .NET Framework, etc.). What's our strategy for documenting packages? If they have to be lumped in with something, then I think ASP.NET Core is probably our best option. It would be nice if there was a way to browse and search through the entire .NET ecosystem of APIs by namespace and filter by things like target frameworks.

**Comment by BillWagner** [comment]
I'll defer to @danroth27 on this one.

**Comment by dend** [comment]
If these packages are not part of built-in API distributions (e.g. .NET Core), we can just document them separately. Would that make sense? @danroth27

**Comment by danroth27** [comment]
@dend They do ship with .NET Core. They ship as part of ASP.NET Core, which ships with .NET Core. But they can also be used elsewhere as normal NuGet packages (ex .NET Framework, Xamarin, UWP)

**Comment by dend** [comment]
@danroth27 thanks for the explanation. In this case, given that they ship as part of ASP.NET Core, it _seems_ like the right approach would be to document these as part of the ASP.NET Core set of libraries. Do we have a list of all the packages that need to be included?

**Comment by danroth27** [comment]
@dend These packages (Microsoft.Extensions.*) already show up with the ASP.NET Core APIs. The question raised here is whether they should also show up with the .NET Core APIs.

**Comment by dend** [comment]
@danroth27 you're right - thanks again for confirming. Would you like to respond to the [Stack Overflow question](https://stackoverflow.com/questions/46914981/why-is-microsoft-extensions-documented-under-asp-net) with an explanation based on [your response here](https://github.com/MicrosoftDocs/feedback/issues/101#issuecomment-399140967)? Once that is live, I will close this issue.

Tangentially, we already [have a plan to integrate package information in documentation](https://github.com/MicrosoftDocs/feedback/issues/72), that will enable users to see what package an API is coming from, which hopefully will reduce confusion as to why certain things belong with other API groups.

**Comment by MV10** [comment]
The explanations above are effectively internal (which team owns what) and perhaps historical (packaged with ASP.NET because that's where they originated in the old .NET), neither of which helps those of us in the outside world find the documentation. Adding assembly/package information to the docs will be nice, but if I can't find the docs in the first place, it doesn't really address this problem.

I know the SO question is just "why?" but in my case the first question was "where?" ... I was writing DI- and config-friendly libraries, and the consuming applications were console utilities and message-triggered Azure Functions apps. It never occurred to me to dig around in an area of the documentation about building web apps because neither area of concern is unique to web apps. The "why?" question came later.

Recently my company (very large enterprise) has started porting things to ASP.NET Core and I've already fielded this question twice in-house after demonstrating all the cool new config extension tricks. As time goes on, I think you're going to hear about this discoverability issue more than you might expect.

**Comment by danroth27** [comment]
The API browser currently groups sets of APIs by "Product". Given that we currently document .NET Core and ASP.NET Core as separate products, I think putting the Microsoft.Extensions.* packages with ASP.NET Core is the most reasonable choice.

That said, I agree with you that this doesn't help you from the perspective of a library author or as someone writing console apps. We should consider cross-linking the corresponding topics in the ASP.NET Core docs from the .NET Core docs.

**Comment by MV10** [comment]
I understand that, but the feedback I was trying to give is that there is no obvious reason they belong to the ASP.NET Core "product" -- to any of us in the outside world, they just randomly ended up there for historical and/or internal reasons, and that makes some docs very hard to find (surprisingly, in some cases Google doesn't even have all of it indexed).

These explanations sound like a parent  giving the non-answer, "Because I said so." 😀

**Comment by dend** [comment]
@MV10 @danroth27 that is reasonable. We try to point people to our "All API" search first to find their desired entities (https://docs.microsoft.com/dotnet/api). Some of the APIs there are not yet indexed because we are not yet redirecting them from MSDN - once we do, you will see the correct pointers in place.
