### ISSUE TITLE
Link/Syntax Issue: WINDOWPLACEMENT Structure

### ISSUE THREAD

**Issue by rockerinthelocker** [MicrosoftDocs/feedback#1010]
Link and syntax refer to tagWINDOWPLACEMENT instead of WINDOWPLACEMENT.

Source: https://docs.microsoft.com/en-us/windows/desktop/api/winuser/ns-winuser-tagwindowplacement

**Comment by Powerhelmsman** [comment]
@ginami Can you take a look at this issue?

**Comment by ginami** [comment]
Hi @rockerinthelocker -- thank you for letting us know; we'll look into the issue.

**Comment by drewbatgit** [comment]
This is by design. The API reference syntax blocks reflect the way that the API is actually defined in the header, which is also the way they are presented by intellisense in Visual Studio. We use the typedef name for the title and the table of contents but we leave the syntax block (and markdown file name) unmodified from the way it is presented in the header file.
