### ISSUE TITLE
Malformed table on DWMWINDOWATTRIBUTE page

### ISSUE THREAD

**Issue by BissetJ** [MicrosoftDocs/feedback#1134]
**Link to article:**
https://docs.microsoft.com/en-us/windows/desktop/api/dwmapi/ne-dwmapi-dwmwindowattribute

Malformed table under the DWMWA_CLOAKED item.  See empty box with exposed markup ( `<table class="clsStd">` ).

**Comment by mimisasouvanh** [comment]
@drewbatgit It looks like the issue has to do with html not being supported in md tables, as enums use md tables.

**Comment by drewbatgit** [comment]
@stevewhims I believe this page is one of yours.

**Comment by stevewhims** [comment]
Thanks, all! I've published a fix to the topic, and that's now live. So I'll go ahead and close this issue. Optional extra info below.

So, source files for topics are .md files. At the moment, those .md files contain a good amount of both markdown and HTML. For a Win32 topic, the content build system takes the authored content from the description sections for each constant in the .md file, and it embeds that inside a HTML table row. So, as long as those descriptions contain only HTML, all is well. And here, everything inside the descriptions is HTML, as it needs to be. In fact, the table itself is/was being rendered fine (modulo the large amount of whitespace before it). However, rather than wrestle with figuring out why the build system was inserting so much whitespace in this particular case, I just restructured the content to remove the table.

We do have other cases where a writer forgets about the Win32 enum topic limitation, and accidentally (but understandably, because it is a markdown file, after all) authors markdown in the description of an enum constant. In a case like that, the markdown isn't rendered properly. We're already tracking a change to the build system to remedy that so that writers can freely author markdown anywhere in any markdown file. But that issue doesn't apply here.
