### ISSUE TITLE
GetProcessInformation function doc has a Content Error

### ISSUE THREAD

**Issue by Cherryzc** [MicrosoftDocs/feedback#1182]
Link to article: https://docs.microsoft.com/en-us/windows/desktop/api/processthreadsapi/nf-processthreadsapi-getprocessinformation

**Problem:**
The first Parameter hProcess‘s description is mistake.This handle must have the PROCESS_SET_INFORMATION access right. It's should be PROCESS_QUERY_LIMITED_INFORMATION

**Comment by BinToss** [comment]
Over four years later and there has been no followup to this issue.
Perhaps the issue name should changed to better explain the issue e.g. "GetProcessInformation states incorrect value for required process access right"

**Comment by mikebattista** [comment]
@stevewhims could you help resolve this longstanding issue? Looks like a simple fix to list the correct required access rights.

**Comment by riverar** [comment]
We can close this issue in favor of PR https://github.com/MicrosoftDocs/sdk-api/pull/1517

**Comment by riverar** [comment]
I'm sure it needs higher rights for some classes. But from a _requirement_ standpoint I think it's okay to say it needs at least PQLI. Was hoping the editors/owners would do some word smithing and/or double-check the impl.

**Comment by stevewhims** [comment]
Thanks for the info and follow-up, everyone! Yes, I think closing this in favor of the PR is best. The PR is already assigned to the writer who owns the topic. So that writer is best placed to confirm with their contacts whether this is how we want to doc it. I could go in now and update the topic, or accept the PR, but it might be better to let the usual owners run with it since they'll have more context than I do.

Thanks!
-Steve
