### ISSUE TITLE
Paste Images Into Documentation Feedback

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#12]
One feature I really love about GitHub issues is the ability to paste images from the clipboard directly to an issue. That's is not working here on docs.microsoft.com 😢 in the new feedback system that uses GitHub.

https://github.com/MicrosoftDocs/TeamBlogFeedback/issues/2

----------
⚠ Idea migrated from UserVoice

**Created By:** Mike DePouw
**Created On:** 2018/03/01 19:13:51 +0000
**Votes at Migration:** 2
**Supporters at Migration:** 1

**Comment by dend** [comment]
#log-suggestion

**Comment by botcrane** [comment]
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=20504) logged.

**Comment by ShevaDas** [comment]
Thanks for the feedback! After talking it over with our devs, we won't be implementing this request. I agree that GitHub's pasting image feature is completely awesome (and use it all the time myself) but in order to implement this on Docs, we'd need to become responsible for the hosting and moderation of possibly hundreds of thousands of images over time, as GitHub doesn't expose the API they use for uploading images to their servers.

If you'd like to include an image in an issue, please upload it to a third party hosting provider or create the issue directly on GitHub's site. We hope you enjoy the new feedback system :)
