### ISSUE TITLE
.NET page for end users

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#127]
There needs to be a page or documentation which is kept up-to-date that outlines in simple, non-technobabble, statements what versions of .NET Framework that end users could or should find on their system.  It should link to each version that is necessary for all programs that have used .NET to work.  It should also specify whether all dependencies from previous versions are included or some.  For example, there is no clear page which would say whether .NET Framework 4.7 includes all the dependencies from 4.0, 4.5, 4.5.1, 4.5.2, 4.6.1, and 4 .6.2.  Similarly, there is nothing stating whether 1.1 and 3.5 covers 1.0 and 2.0/3.0 respectively.

----------
⚠ Idea migrated from UserVoice

**Created By:** Brian
**Created On:** 2017/07/29 16:14:47 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by Powerhelmsman** [comment]
@mairaw Can you take a look at this?

**Comment by mairaw** [comment]
I think we should close this.

http://dot.net is supposed to be the home for non-techie, more high-level information.

Version that comes with your machine depends on what OS you have. A lot of the versions this person lists is already out of support (1.0, 2.0, 3.0, etc.)

We have end-user guides for installation: https://docs.microsoft.com/en-us/dotnet/framework/install/

For developers, we go a bit deeper and explain for example the in-place mechanism: https://docs.microsoft.com/en-us/dotnet/framework/install/guide-for-developers

Also, not sure if I understand the dependency question. 

Since we can't reach out to this person any longer to ask clarifying questions and what they're trying to do, I'd vote to close.
