### ISSUE TITLE
Missing interface in Interop.UPNPLib under Windows 10

### ISSUE THREAD

**Issue by chrisschm** [MicrosoftDocs/feedback#1319]
**Describe the bug**
IUPnPDescriptionDocumentCallback interface missed in Interop.UPNPLib in Windows 10 1809 described on Microsoft DOCs: https://docs.microsoft.com/de-de/windows/desktop/api/upnp/nn-upnp-iupnpdescriptiondocumentcallback

**To Reproduce**
1. Using Visual Studio Community 2017
2. Insite a project added a reference to Interop.UPNPLib
3. Open the object-catalogue (F2)
4. See error (screenshot below)

**Expected behavior**
Would like to see a completed UPnPLib 

**Screenshots**
![image](https://user-images.githubusercontent.com/47923480/54860231-7a1fc600-4d17-11e9-8229-adf161b2e8ad.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 1809 (17763.379)

**Additional context**
A Visual Basic programmer (i am not realy a programmer, hobbyist) wants to have it easy, no chance to get informations from c/c++ header files. Wondering when a documentation does not match with reality (or libraries).

**Comment by chrisschm** [comment]
Nothing changed yet to the issue - no news heared.

- OS: Windows 10 Pro 1903 (18362.476)
- Visual Studio Community 2019

Still the same issue.

**Comment by chrisschm** [comment]
Going forward... Nothing changed yet to the issue - no news heared.

- OS: Windows 10 Pro 21H2 (19044.1415)
- Visual Studio Community 2022

Still the same issue.

**Comment by drewbatgit** [comment]
@chrisschm I apologize for the long delay on this issue. I have recently taken ownership of this documentation and so I don't have subject matter expertise in these particular APIs, but I notice that this is a callback interface, so I would not expect that this would have a lib implementation since clients would be expected to implement the interface. Our reference documentation pipeline uses reflection over the SDK *header* files to match the API surface, we do not scan the libs. So, if you believe the interface should be showing up in the object browser, it would be an issue on the product/dev side. Since issues in this repo are specifically for documentation issues, I recommend you open an issue with community of experts and Microsoft Engineers over at [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/windows-uwp.html).

**Comment by chrisschm** [comment]
Recently in April 2019.. Yes it must be part of the typelib. Otherwise the compiler isnt able to proof an implementation as a correct one. But thanks for the answer at least.

I think it isnt my job to find out who should work on that issue. I have made my memo to Microsoft and they should be able to redirect it correctly inside the offices. I'll not ask again. The dokumentation seems to be correct and you may close the issue.
