### ISSUE TITLE
Integrate with Visual Studio so that F1 help goes to correct method overload

### ISSUE THREAD

**Issue by docs-product** [MicrosoftDocs/feedback#134]
If you press F1 on a .NET method call in Visual Studio, it will take you directly to the .NET API documentation for that method.  However, it takes you to the top of the page.

Please work with the Visual Studio IDE team so that F1 Help takes you directly to the #AnchorTag for the specific overload that the code is using.  For example:

1. Create a C# project in Visual Studio, and type: new StringBuilder(100, 100);
2. Click on StringBuilder.
3. Press the F1 key.
4. Visual Studio goes to a redirect page on msdn.microsoft.com.
5. The page redirects to docs.microsoft.com and goes to the top of the page for the StringBuilder constructor.

Instead of going to the top of the page, it should go to the #anchorTag for the StringBuilder(int, int) overload.

The StringBuilder constructor only has 6 overloads, but some methods have a lot more.  The user shouldn't have to hunt for the correct overload link when Visual Studio already knows which one is being used in the code.

----------
⚠ Idea migrated from UserVoice

**Created By:** Tao Yue
**Created On:** 2017/06/19 00:24:00 +0000
**Votes at Migration:** 2
**Supporters at Migration:** 2

**Comment by rloutlaw** [comment]
@docs-product Reviewing this as won't do-the resolution here is just handle overloads better in the doc. By jumping to the exact signature, we skip the chance to show the other options  (some of which may be better that the user wasn't aware of ) for the method to be called and documentation that sets guidance and context because we deep link to the page.
