### ISSUE TITLE
Please provide a sample output for Get/Post response of Each API for comparison during implementation.

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#139]
_No details provided._

----------
⚠ Idea migrated from UserVoice

**Created By:** Sernapally Anurag
**Created On:** 2017/05/22 12:28:42 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by hellosnow** [comment]
@dend is there any other details on this issue? Or how can I track from the original user voice? Thanks

**Comment by hellosnow** [comment]
@Powerhelmsman @dend is there any other details on this issue?

**Comment by Powerhelmsman** [comment]
@hellosnow The issue was migrated from User Voice. I don't know the user's GitHub account. So no way to clarify the detail for you. So if you think the description is not enough to create a feature, we have to close as no enough information. If someone can provide the detail later, we can reopen it and continue the discussion.
