### ISSUE TITLE
SW_MAXIMIZE and SW_SHOWMAXIMIZED have same value 3, which to use.

### ISSUE THREAD

**Issue by luyaok** [MicrosoftDocs/feedback#1492]
**Link to article:**
https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-showwindow

**Problem:**
In the documentation on the ShowWindow function, there is a list of values for the int parameter nCmdShow.

However, there are 2 entries with the same 3 value, SW_MAXIMIZE and SW_SHOWMAXIMIZED.

Which one is it?

Thank you.

MSDN thread: https://social.msdn.microsoft.com/Forums/windowsdesktop/en-US/d2a8a7cf-1a11-4608-848e-fa447195578a/showwindow-ncmdshow-parameter-several-values?forum=windowsgeneraldevelopmentissues

**Comment by ryanmajidi** [comment]
@GrantMeStrength Can you please take a look at this?

**Comment by GrantMeStrength** [comment]
This is correct - both values are valid.

**Comment by mairaw** [comment]
I think the problem the customer is reporting here is that both SW_SHOWMAXIMIZED and SW_MAXIMIZE show the value 3. One should be different no?

**Comment by Venryx** [comment]
The current contents are confusing because there are two names (SW_MAXIMIZE, SW_SHOWMAXIMIZED) mapping to the same value.

One might say: They're just alternate names for the same behavior.

However, if that's true, then the description of the behavior of the two entries should be the same. They're not. One says, "Maximizes the specified window.", and the other says, "Activates the window and displays it as a maximized window."

Thus, one claims to activate the window, while the other does not. This is bad documentation since they have the same value, thus the same behavior. (thus one of the descriptions is inaccurate, or at least incomplete)
