### ISSUE TITLE
Microsoft"Docs" is not worth it's Name - it's a shame, what Microsoft creates (generates?)

### ISSUE THREAD

**Issue by schittli** [MicrosoftDocs/feedback#1512]
**The bug**
While Micorosft is proud to present its exorbitant profits to the world, we can watch the product quality degenerate. For example, more and more documentation is reduced to its minimum as if a stupid document generator would generate it.

The result: 
**As developers who still support the M$ platform,** we miss the professional documentation more and more often.

**To Reproduce**
Let's see that we can do by using `DWMWA_EXTENDED_FRAME_BOUNDS`:
1. Open [Microsoft"Docs" for `DwmGetWindowAttribute` function](https://docs.microsoft.com/en-us/windows/desktop/api/dwmapi/nf-dwmapi-dwmgetwindowattribute)
2. OK, we must navigate to [Microsoft"Docs" for `dwAttribute`](https://docs.microsoft.com/de-de/windows/desktop/api/dwmapi/ne-dwmapi-dwmwindowattribute)
3. Try to understand what e.g. `DWMWA_EXTENDED_FRAME_BOUNDS` is doing. Some most basic and usual questions:
- What is returned in dwAttribute, pvAttribute and cbAttribute?
- What's the issue if pvAttribute sometimes returns the (wrong) x coordinate of -32000?
- Is it a bug or an undocumented error code?
**If it's a bug, then it's sad for M$** because you'll get the bug reported too late, because the expected behavior is not documented. 
**If it's an undocumented error code, then it's sad for M$** because your developers (which are writing Software for your platform) realize that Microsoft is trampling on their needs.

**Expected behavior**
A clear and concise description of all functions

**Desktop (please complete the following information):**
(everything in docs.microsoft.com)

**Comment by ryanmajidi** [comment]
@GrantMeStrength Can you please take a look at this issue?

**Comment by stevewhims** [comment]
Hi, @schittli, thanks for filing this GitHub issue; and my apologies for the issues themselves and my delay in responding. I'll describe the steps I've taken so far to address the issues, and the question that remains.

First, I update the conceptual topic [Enable and control DWM composition](https://docs.microsoft.com/windows/desktop/dwm/composition-ovw) to make it clear what the relationship is between a) the attribute flag passed to DwmGetWindowAttribute and DwmSetWindowAttribute, and b) the type of the attribute value that those functions retrieve/set. I added more code examples to that topic, include specifically a code example for DWMWA_EXTENDED_FRAME_BOUNDS, which was a scenario that you mentioned.

Next, I went through the three API reference topics below, and made sure the descriptions of each of the parameters/fields was clear, and I added a very prominent link (at the beginning of each of these three API ref topics) to the conceptual topic, so that readers would know from the start that code examples (and conceptual content) exist, and where to find them.

* [DwmGetWindowAttribute function](https://docs.microsoft.com/windows/desktop/api/dwmapi/nf-dwmapi-dwmgetwindowattribute)
* [DwmSetWindowAttribute function](https://docs.microsoft.com/windows/desktop/api/dwmapi/nf-dwmapi-dwmsetwindowattribute)
* [DWMWINDOWATTRIBUTE enumeration](https://docs.microsoft.com/windows/desktop/api/dwmapi/ne-dwmapi-dwmwindowattribute)

I also contacted the product engineers asking about that -32000 value that you mentioned. We're still looking into that, but is there anything further that you can tell me about that value and the conditions under which you saw it? Is it possible that you were querying the bounds of a minimized window? Did you raise a support call for that issue with Microsoft support? That value of -32000 is the only outstanding issue here, I think, and if I can determine the conditions under which it's returned, and if there's confidence that the behavior of the API won't change any time soon with respect to that value, then I will document it.

Thanks!
Steve

**Comment by stevewhims** [comment]
Hi, @schittli, I've gone ahead and resolved the issues that you found. I've detailed my fixes above. I'll go ahead and close this issue now, since it feels resolved. But please re-open it, or file news one, if necessary.

Thanks!
Steve
