### ISSUE TITLE
Extension Methods section title not localized in .NET API Browser

### ISSUE THREAD

**Issue by MSDN-WhiteKnight** [MicrosoftDocs/feedback#1571]
**Describe the bug**
Extension Methods section title is not translated in .NET API Browser in localized documentation

**To Reproduce**
1. Go to https://docs.microsoft.com/ru-ru/dotnet/api/system.array?view=netcore-3.0#extension-methods
2. See that "Extension Methods" is shown in english

**Expected behavior**
Extension Methods section title should be translated.

**Screenshots**

![screenshot](https://i.stack.imgur.com/5YHu9.png)

**Comment by ryanmajidi** [comment]
@SonjaSaltzman Can you please take a look at this issue?

**Comment by SonjaSaltzman** [comment]
@DavidPrio cc: @JasonCard

**Comment by CeciAc** [comment]
Hello, @MSDN-WhiteKnight 

Your feedback is much appreciated.
Since your comments are specific to the localization of the documentation, we have moved this issue to the corresponding localization repository and we will close this one.

Please review the status of this issue here https://github.com/dotnet/dotnet-api-docs.ru-ru/issues/25

Kind regards,
Microsoft DOCS International Team
