### ISSUE TITLE
TIMERPROC doc missing calling convention

### ISSUE THREAD

**Issue by clandrew** [MicrosoftDocs/feedback#1650]
**Link to article:**
https://review.docs.microsoft.com/en-us/windows/desktop/api/winuser/nc-winuser-timerproc

**Problem:**
The sample code will fail to compile generally because it is missing the calling convention, CALLBACK (i.e., stdcall)

**Comment by ryanmajidi** [comment]
@GrantMeStrength Can you please take a look at this issue?

**Comment by clandrew** [comment]
For whoever gets to it: the problem is just this one off page, it's a systemic issue in the docs where calling convention is omitted for C++ methods. 

In most situations, calling convention doesn't matter for purposes of apps trying to call the function, but it does matter when implementing callbacks.

I briefly looked into trying to find a way to fix this individual page. The "Syntax" section looks to be machine-generated, no way to hook it. Someone with more expertise on the system might know how to hook it. I'd be okay with fixing this individual page in the short term, if there was even a way to do that. For the bigger systemic issue, I'm leaving it up to the doc team to decide on whether to do it and how.

**Comment by stevewhims** [comment]
On July 2, when Claire mentioned the issue to me, I filed bug [102782 Win32 :: syntax block :: calling convention is omitted](https://ceapex.visualstudio.com/Engineering/_workitems/edit/102782). That bug is triaged and assigned to dev. All the info here (and more) is in that bug. I suggest we close this GitHub issue, since we're tracking the work internally.
