### ISSUE TITLE
So many issues, typos, format issues

### ISSUE THREAD

**Issue by WolfMachine** [MicrosoftDocs/feedback#1683]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
Tell us where exactly a problem occurs.
1: https://docs.microsoft.com/en-us/windows/desktop/learnwin32/your-first-windows-program
2: https://docs.microsoft.com/en-us/windows/desktop/learnwin32/your-first-direct2d-program

**Problem:**
What's wrong with the article?
1: Format issue; return 0 in the wrong place.

2: Format issue

**Comment by ryanmajidi** [comment]
@GrantMeStrength Can you please take a look at this issue?

**Comment by QuinnRadich** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. Due to the sheer volume of feedback in our repo, we are currently prioritizing new Issues. If you believe your feedback is still actionable, let us know either directly in this thread or by filing a new Issue and we’ll work to incorporate the suggestions into the documentation. Though the Issue will be marked as Closed, I will monitor any replies that come afterwards so feel free to treat this like an open Issue. Many thanks.

If you do create a new issue, I'd recommend that you add a few more specifics about the observed formatting issues on this page. They may have already been resolved since you initially created the issue.
