### ISSUE TITLE
wrong code

### ISSUE THREAD

**Issue by workeraccount001** [MicrosoftDocs/feedback#1685]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2003/cc784966(v=ws.10)

**Problem:**
What's wrong with the article?
section example:
PROCESS GET NAME /FORMAT:XML.XSL /TRANSLATE:BASICXML
should be 
PROCESS GET NAME /FORMAT:XML /TRANSLATE:BASICXML

**Comment by ryanmajidi** [comment]
@GrantMeStrength Can you please take a look at this issue?

**Comment by GrantMeStrength** [comment]
Thanks for taking the time to let us know about this issue and we sincerely apologize for the delayed response. Due to the sheer volume of feedback in our repo, we are currently prioritizing new Issues, and as this issue is in an older area of the docs which do not get regular updates, it's been at the back of the queue for a while. Though the Issue will be marked as Closed, I will monitor any replies that come afterwards and if we have time will prioritize the fix as best we can. Thanks! -john
