### ISSUE TITLE
Cookie Handling in WinHTTP

### ISSUE THREAD

**Issue by Starodub-A-V** [MicrosoftDocs/feedback#1741]
"To disable cookie handling, the WinHTTP client application calls the WinHttpSetOption function with the dwOption parameter set to WINHTTP_OPTION_DISABLE_FEATURE, and the lpBuffer parameter set to WINHTTP_DISABLE_COOKIES."
lpBuffer isn't to set in WINHTTP_DISABLE_COOKIES
Error: "argument of type is incompatible with parameter of type"

**Comment by ryanmajidi** [comment]
@GrantMeStrength Can you please take a look at this issue?

**Comment by GrantMeStrength** [comment]
Thanks for taking the time to let us know about this and we sincerely apologize for the delayed response. Due to the sheer volume of feedback in our repo, we are currently prioritizing new Issues. If you believe your feedback is still actionable, let us know either directly in this thread or by filing a new Issue and we’ll work to incorporate the suggestions into the documentation. Though the Issue will be marked as Closed, I will monitor any replies that come afterwards so feel free to treat this like an open Issue. Many thanks! - john
