### ISSUE TITLE
CHOOSECOLOR structure is just .... completely missing

### ISSUE THREAD

**Issue by nakst** [MicrosoftDocs/feedback#1781]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
https://docs.microsoft.com/en-us/windows/desktop/api/Commdlg/ns-commdlg-tagchoosecolora

**Problem:**
It doesn't exist. What happened to the documentation for this structure?

**Comment by nakst** [comment]
[TVITEM](https://docs.microsoft.com/en-us/windows/desktop/api/commctrl/ns-commctrl-tagtvitema) is also missing.

**Comment by drewbatgit** [comment]
Thanks for reporting documentation issues. These two issues are related to the way that we name files in our new content management system, which was modified slightly since these pages were initially published. Also, in our new system, the ANSI (*A) and Unicode (*W) APIs are documented separately. The reference pages for these pages are here:

https://docs.microsoft.com/en-us/windows/win32/api/commdlg/ns-commdlg-choosecolora~r1
https://docs.microsoft.com/en-us/windows/win32/api/commctrl/ns-commctrl-tvitema

I hope that the search engines will reindex these pages so that you can find these new URLs with search. As a stop-gap, you can view all APIs in a header just by navigating to the page for the header - which is just the URL up until the last forward slash:

https://docs.microsoft.com/en-us/windows/win32/api/commdlg

I will continue to investigate this issue and see if there's anything we can do to help users find these pages better. Thanks again for your feedback.

**Comment by nakst** [comment]
Instead of *hoping* that search engines reindex these pages, there are a few tasks that could be done to help ease the transition:
1. Update links in other articles to point to the location of the moved pages.
2. Add redirects from the old pages to the new pages.
3. Update your own search tool in MSDN so that it puts exact article name matches at the top of the search results.

As a stop-gap, I will continue to use the offline "MSDN Library for Visual Studio 2008" that you forgot to delete from the Microsoft website.
