### ISSUE TITLE
Missing version information - especailly in Intune Hybrid Documenation we miss SCCM version

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#189]
Documentation of Intune features and functionalities should always contain information to which Intune and Configuration Manager version the documentation relates to. Not having the information it's always hard to figure out what should be available/possible in Intune Hybrid (having probably not the latest ConfigMgr version installed). E.g. when a features requires ConfigMgr 1606 it should be mentioned in the documentation ("Available for Intune Hybrid starting ConfigMgr 1606") . This would make life much more easier. :-)

----------
⚠ Idea migrated from UserVoice

**Created By:** Thomas
**Created On:** 2016/11/16 12:40:59 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by dend** [comment]
@aczechowski @mestew as FYI on the request. Given that this is a content issue, it will be closed soon, but I wanted to put it on your radar.

**Comment by aczechowski** [comment]
@barlanmsft @dougeby as well. 
@dend do you have a link to the original UV idea?

**Comment by dend** [comment]
@aczechowski you can find it [here](https://msdocs.uservoice.com/forums/364242-site-feedback/suggestions/17131135-missing-version-information-especailly-in-intune). FYI the UserVoice site is in read-only mode as we moved here (to GitHub) for feature requests.

**Comment by dend** [comment]
@aczechowski any updates on this item?

**Comment by aczechowski** [comment]
I can't speak for Intune, but for SCCM and hybrid content we *often* note this, as long as there is some delta for a supported versions. For a new feature, we'll say "starting in version 1802...". But then with the release of 1802, we started to remove such statements for 1702 and earlier releases. I can't say it happens in *every* instance, though. So my suggestion is to close this issue, as it's not really actionable in this state. We just recently enabled GitHub Issues for the SCCM docs repository. If there are specific instances on SCCM articles where customers have questions/concerns about this issue, they should file feedback directly on those articles so that we can track in our backlog.
