### ISSUE TITLE
xaminals demo does not build

### ISSUE THREAD

**Issue by mjfreelancing** [MicrosoftDocs/feedback#1952]
**Describe the bug**
The download at https://docs.microsoft.com/samples/xamarin/xamarin-forms-samples/userinterface-xaminals/ does not build

**To Reproduce**

1. Download demo frrom https://docs.microsoft.com/samples/xamarin/xamarin-forms-samples/userinterface-xaminals/

2. Build

**Expected behavior**
The demo should build

The error (6 of them) is in AppShell.xaml

XLS0503
A value of type 'ShellContent' cannot be added to a collection or dictionary of type 'IList'.

I upgraded the demo to the latest version of Xamarin.Forms (4.2.0.815419) and the problem went away.

Note: The xaml still shows a warning with blue squiggly lines but it builds, deploys, and runs. Should the xaml be updated too ?

**Comment by mairaw** [comment]
@conceptdev can you take a look at this feedback?

**Comment by conceptdev** [comment]
Thanks for the feedback @mjfreelancing – it builds and runs fine in Visual Studio for Mac (stable release) without having to update NuGets. 

Note that I also see the errors you refer to in the **AppShell.xaml** page while _editing_ the XAML, but since it compiles and runs successfully, that is more likely to be a bug in the IDE that [should be reported inside Visual Studio](https://docs.microsoft.com/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019).

Can you add a screenshot of the errors, and perhaps some additional information about your setup?

**Comment by mjfreelancing** [comment]
How strange. As I am using Windows, I decided to delete the project, download again (I downloaded the previous version only a few hours ago so I assume it is the same), and re-create the error. Oddly, it built this time. I have no explanation.

I'll report the other issue within the IDE (screen shot attached for reference).

![warnings](https://user-images.githubusercontent.com/17043225/65367684-6dedd480-dc78-11e9-8113-e183a058a9c5.jpg)

**Comment by mjfreelancing** [comment]
Let's hope the IDE team respond. None of my previous reports have ever been responded to beyond 'Triaged'.

Here's the new report: https://developercommunity.visualstudio.com/content/problem/742148/unnecessary-warnings-with-xamarin-forms-shell.html

**Comment by conceptdev** [comment]
Thanks, I see the same underlining/errors in the XAML editor on macOS. I added a screenshot to the developercommunity item, so I'll see any responses as well.

Despite the fact that this does appear to be an IDE bug, I'll also pass on your suggested fix

>If I move the ShellContent into an explicit &lt;Tab> then the warnings go away.

which might reduce confusion for other users (regardless of whether it "should" be necessary or not).

Appreciate the feedback.

#please-close
