### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by ShinjiFunabiki** [MicrosoftDocs/feedback#1969]
Microsoft Forms Pro の試用にサインアップする
Microsoft Forms Pro は、2019年 7 月 1 日に一般提供されました。 Forms Proを試すには、30日間無料トライアルにサインアップできます。 試用期間の終了後、 Microsoft Forms Pro を**スカイ**続けるには有料ライセンスが必要です。 

スカイ→使い

**Comment by mairaw** [comment]
What is the page you're seeing this @ShinjiFunabiki?

/cc @CeciAc

**Comment by ShinjiFunabiki** [comment]
Sorrry. here
https://docs.microsoft.com/ja-jp/forms-pro/get-started

**Comment by CeciAc** [comment]
Hello, @ShinjiFunabiki
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hi @mairaw 
We have the linguistic assessment for this issue but cannot make the implementation since this is out of our scope, please, forward it to the correct team:

Source: Microsoft Forms Pro is generally available on July 1, 2019. To try Forms Pro, you can sign up for a free 30-day trial. After the trial period, you will need a paid license to continue using Microsoft Forms Pro.

Current translation: Microsoft Forms Pro は、2019年 7 月 1 日に一般提供されました。 Forms Proを試すには、30日間無料トライアルにサインアップできます。 試用期間の終了後、 Microsoft Forms Pro をスカイ続けるには有料ライセンスが必要です。

Final translation: Microsoft Forms Pro は、2019 年 7 月 1 日に一般提供されました。 Forms Pro を試すには、30 日間無料トライアルにサインアップできます。 試用期間の終了後、Microsoft Forms Pro を使い続けるには有料ライセンスが必要です。

**Comment by mairaw** [comment]
@sbmjais do you know who is the localization team for the Forms Pro content?

**Comment by DavidPrio** [comment]
@SunnyDeng may be you can help investigate as well?

**Comment by SunnyDeng** [comment]
Hi @vinceno @krisre , do you own this repo https://github.com/MicrosoftDocs/forms-pro-pr.ja-jp/?

**Comment by vinceno** [comment]
+Marian, who manages this repo loc

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by DavidPrio** [comment]
@vinceno FYI I don't think any Marian was tagged here...

**Comment by vinceno** [comment]
@mhogan73

**Comment by mhogan73** [comment]
I will share with our localization team. Thx

**Comment by mhogan73** [comment]
The updated topic is now published Live. @CeciAc @ShinjiFunabiki

**Comment by mairaw** [comment]
Closing this issue then.
