### ISSUE TITLE
404 on https://docs.microsoft.com/en-us/windows/uwp/design/layout/xaml-basics-adaptive-layout

### ISSUE THREAD

**Issue by nick-goloborodko** [MicrosoftDocs/feedback#205]
The page above gives a 404 error when following a link

**Comment by dend** [comment]
@nick-goloborodko where did you follow this from?

**Comment by mairaw** [comment]
I think the problem is here: https://github.com/MicrosoftDocs/windows-uwp/blob/a062114cd37ef2ab6f82b3463a8b471837df7947/.openpublishing.redirection.json#L100

It should probably be redirecting here instead: https://docs.microsoft.com/en-us/windows/uwp/design/basics/xaml-basics-adaptive-layout

/cc @mukin

**Comment by dend** [comment]
@kevinyr @mijacobs can you help with this request?

**Comment by dend** [comment]
@mairaw I fixed the redirect. The content change might take a bit.
