### ISSUE TITLE
Permalinks for Anchor Links

### ISSUE THREAD

**Issue by spottedmahn** [MicrosoftDocs/feedback#2107]
**Is your feature request related to a problem? Please describe.**
Please see this [dev community issue](https://developercommunity.visualstudio.com/content/problem/796811/bad-link-for-how-do-i-deploy-project-artifacts-wit.html).  I suspect the link was valid at one point but some renamed the header in the doc page and that broke the anchor link.  This is not the first time I've come across this.

![image](https://user-images.githubusercontent.com/14079228/67951624-46b4ec00-fbc2-11e9-90ef-8c6cf8d68626.png)

**Describe the solution you'd like**
Provide some way of preventing anchor links from breaking when headers are renamed.

**Describe alternatives you've considered**
None

**Additional context**

**Comment by docs-product** [comment]
Thanks for the feedback, @spottedmahn - currently, the anchor links are generated automatically from the header, therefore if the content maintainer updates those, the links will change as well. The reason this functionality is in place is because anchor links should be consistently mapped to the text (i.e. be predictable).
