### ISSUE TITLE
Clarify what NumricUpDown.DecimalPlaces property does

### ISSUE THREAD

**Issue by Tanya-Solyanik** [MicrosoftDocs/feedback#2146]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem** (if available).

**Link to article:**
https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.numericupdown.decimalplaces?view=netframework-4.8#System_Windows_Forms_NumericUpDown_DecimalPlaces

**Problem:**
We received feedback that it's not clear that `DecimalPlaces` property controls only the display value and does not affect the actual `Value` property of this control.

Current top most line:
`Gets or sets the number of decimal places to display in the spin box (also known as an up-down control).`

Suggested change:
`Gets or sets the number of decimal places to display in the spin box (also known as an up-down control). This property does not affect the <see cref=System.Windows.Forms.NumericUpDown.Value> property.`

**Comment by amelvill** [comment]
Posted this here by request from Zheng Li on [Connect](https://developercommunity.visualstudio.com/content/problem/807674/numericupdown-does-not-round-to-enforce-decimalpla.html?childToView=819515#comment-819515)

- What do you think about making [Constrain](https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/NumericUpDown.cs,e4853fb24dce9211) `protected virtual` instead of `private` in future versions of the .NET framework?

- What would you think of adding a workaround to the docs showing how to make a `NumericUpDown` round? (e.g., using the Validating event?)

**Comment by mairaw** [comment]
I'd say that for bullet #1, there are no future work happening for .NET Framework, only servicing. All the improvements are now being made on .NET Core. You can file an issue at https://github.com/dotnet/winforms for the team to consider.

For request #2, @Tanya-Solyanik can you comment on that suggestion?

**Comment by Tanya-Solyanik** [comment]
>For request #2, @Tanya-Solyanik can you comment on that suggestion?

This workaround is available and discoverable on Stackoverflow: https://stackoverflow.com/questions/21811303/numericupdown-value-not-rounded-to-decimalplaces, I don't see the need to copy it over.
