### ISSUE TITLE
SME Profile Engagement Link broken

### ISSUE THREAD

**Issue by julians1966** [MicrosoftDocs/feedback#2159]
**Link to article:**
https://docs.microsoft.com/en-us/learn/certifications/posts/help-us-create-exams-and-learning-content

**Problem:**
Link "Joining the SME Profile engagement on Microsoft Collaborate_v2.pdf" is https://query.prod.cms.rt.microsoft.com/cms/api/am/binary/RE3N3DO and this returns {"Code":"DocumentNotFound","Message":"StorageDocumentNotFoundException : Could not find document with id 'RE3N3DO', tenant 'am'. ","Resource":null}

**Comment by mairaw** [comment]
@bipach you seem to be the owner of this. Can you take a look?

**Comment by h0s** [comment]
@julians1966  i face the same issue and since this was not answererd by the MSFT team , here is an alternative[ link](https://www.microsoft.com/en-us/learning/community-blog-post.aspx?BlogId=8&Id=375069) that you can use to find the [pdf  ](http://borntolearn.mslearn.net/cfs-file/__key/telligent-evolution-components-attachments/01-08-00-00-00-37-50-69/Joining-the-SME-Profile-engagement-on-Microsoft-Collaborate_5F00_v2.pdf)document and all information about this program

**Comment by julians1966** [comment]
Link is working again
