### ISSUE TITLE
Registration of new bots for skype

### ISSUE THREAD

**Issue by zharikovartem** [MicrosoftDocs/feedback#2176]
Good day. I was faced with the urgent need to create a Skype bot, but registration of new bots was terminated.

In this regard, I have several questions:

1) Will an alternative technology for automatically sending messages to skype (possibly through teams) be provided?

2) will registration of new bots be renewed, if so how soon?

3) is it possible to register a bot as an exception? Since it is extremely important for the further development of our software product.

**Comment by mlottner** [comment]
@zharikovartem Thanks for commenting on our docs feedback channel!

To receive the product response you requested, make sure to use the product support channel instead of the docs feedback forum. 

Use the [Skype for Business](https://docs.microsoft.com/en-us/skypeforbusiness/skype-for-business-online) product support channel for your inquiry.
