### ISSUE TITLE
Transform matrix is wrong for SetWorldTransform documentation.

### ISSUE THREAD

**Issue by Ma-XX-oN** [MicrosoftDocs/feedback#2208]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem** (if available).

**Link to article:**
https://docs.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-setworldtransform

**Problem:**
The transform matrix is incorrect.  The general translation/rotation matrix should be:

matrix: |   | &nbsp;
------ | ----- | -----
eM11 | eM12 | eDx
eM21 | eM22 | eDy
0 | 0 | 1

See http://planning.cs.uiuc.edu/node99.html.

The matrix provided doesn't even line up with the algorithm specified above it in the document.

**Comment by stevewhims** [comment]
Hi, @Ma-XX-oN, and thanks for filing this issue. You're right, the matrix does need work. It's not just the eDx and eDy elements that need to move: the matrix needs to be inverted to make it correct. That'll make it match the formula (which I can't change). The element notation in the matrix will have to be col-row (instead of row-col), but I'll make that clear in the Remarks. The fix should be live by end of day Monday at the latest, but I'll monitor it.

-Steve

**Comment by stevewhims** [comment]
UPDATE: The fix is now live.

Thanks again!
Steve
