### ISSUE TITLE
Search for "Move pay as you go to CSP subscription" finds a link but then redirects to partner site - impossible to find document

### ISSUE THREAD

**Issue by MGodfrey50** [MicrosoftDocs/feedback#2386]
A search for "move pay as you go subscription to CSP" results in the following, exactly right, except that selecting this land you on the partner page and you cannot find /access the doc.  Super frustrating.
____________________
Migrate Azure subscriptions from Pay-As-You-Go to Azure CSP
https://docs.microsoft.com/.../migration/migration-from-payg-to-csp

Migrate Azure subscriptions from Pay-As-You-Go to Azure CSP. 01/19/2019; 2 minutes to read; In this article. Here is how to assess and migrate existing Azure subscriptions from the Pay-As-You-Go program (sometimes called Azure Direct) to the Azure Cloud Solution Provider (Azure CSP) program.
_________________

Goes to  https://docs.microsoft.com/en-us/partner-center/  with no way to find the doc.

**Comment by JasonWHowell** [comment]
Hi @MGodfrey50 

Google and other search engines can cache links to pages that are no longer available until the index is rebuilt/and our docs site is recrawled. 

Sounds like we may have archived the documentation page you were searching for, and redirected the link to the base of the partner-center since there is no exact replacement doc for that page.

This article might help- 
https://docs.microsoft.com/en-us/azure/cost-management-billing/manage/switch-azure-offer
https://docs.microsoft.com/en-us/azure/cost-management-billing/manage/transfer-subscriptions-subscribers-csp

Thanks, Jason
#please-close
