### ISSUE TITLE
Missing an exception on page for Image.FromStream method

### ISSUE THREAD

**Issue by dennis-thomas-o** [MicrosoftDocs/feedback#2582]
**Link to article:**
https://docs.microsoft.com/en-us/dotnet/api/system.drawing.image.fromstream

**Problem:**
There is another ArgumentException which is not mentioned in the Exception sections — “Parameter is not valid.”. I’m using .NET Framework 4.6.1.

**Potential solution:**
Please list this possibility and add an explanation for it as well.

**Comment by gewarren** [comment]
@carlossanlop

**Comment by carlossanlop** [comment]
@safern is the area owner for System.Drawing. Can you please help add this missing documentation?

**Comment by safern** [comment]
@carlossanlop can this be migrated to the docs repo and assigned to me, or how is this repo different from? https://github.com/dotnet/dotnet-api-docs

**Comment by gewarren** [comment]
This is the general feedback site for all of docs.microsoft.com. I don't think we can do a straight transfer of the issue since they are in different organizations (MicrosoftDocs and dotnet). @mairaw What have you done in the past - just created a new issue in the specific repo?

**Comment by carlossanlop** [comment]
It's possible to transfer issues from different orgs if you use: https://hubbup.io/Mover
This issue will be closed and a new one will be opened in the other repo, with all the comment history copied.
But since @safern and I don't have write permissions in this repo so that it gets closed, we cannot transfer it to dotnet-api-docs.
Can you please try it, @gewarren?

**Comment by gewarren** [comment]
I don't have write perms in this repo either, but I think that @mairaw does. Maira, could you transfer the issue?

**Comment by gewarren** [comment]
This issue was moved to dotnet/dotnet-api-docs#4051
