### ISSUE TITLE
Spelling Mistakes In Knowledge Document

### ISSUE THREAD

**Issue by jagdeepgupta813** [MicrosoftDocs/feedback#265]
# Correct Spelling Mistakes
Spelling mistake in the  document, [https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2003/cc772774(v=ws.10)](How DNS works)
## Issue Details
I would like to correct a spelling mistake (or my understanding about the word) "interative " in the Document refereed above.
Its used in 7th point under subheading "DNS Query Types"

**Comment by svick** [comment]
That's a Windows Server 2003-specific page, which I think is not likely to be updated because of a typo. [I couldn't find that misspelling in the current version of the documentation](https://github.com/MicrosoftDocs/windowsserverdocs/search?q=interative), so I'm not sure there's anything to be done here.

**Comment by Powerhelmsman** [comment]
@jagdeepgupta813 This content is archived and no longer supported.
