### ISSUE TITLE
“Enter focus mode”

### ISSUE THREAD

**Issue by keycal** [MicrosoftDocs/feedback#2781]
In Microsoft Build Tutorial, c#, there is a reference to “Enter focus mode”.   I am using Visual Studio 2019 in interactive mode.  Where is this action to pu in “focus mode”?

![06308926-E451-4A93-9DE9-7C239A73547D](https://user-images.githubusercontent.com/39708340/82767977-b823e880-9df9-11ea-9346-2737c5bde99d.png)

Harvey Hecker
Keycalinc@hotmail.com

**Comment by svick** [comment]
This is a browser-based tutorial, you won't need Visual Studio to follow it. If you're on a mobile device, you should see the "Enter focus mode" button at the bottom of the page. Though following the tutorial from your PC's browser is probably a better choice.

**Comment by mairaw** [comment]
@BillWagner FYI since this is re. https://docs.microsoft.com/en-us/dotnet/csharp/tutorials/intro-to-csharp/branches-and-loops?tutorial-step=1

You should see the Enter focus mode on the right side of the page:
![image](https://user-images.githubusercontent.com/12971179/86093588-0fa21d80-ba64-11ea-86e2-43196d1c48f1.png)

Let us know if you need any other help.
