### ISSUE TITLE
SystemEvents not working from a Windows Service

### ISSUE THREAD

**Issue by Tam66662** [MicrosoftDocs/feedback#2860]
**Describe the bug**
The documentation on [SystemEvents ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.win32.systemevents?view=dotnet-plat-ext-3.1) gives a clear example (Example 2) of how to hook SystemEvents into a Windows Service, by creating a hidden Form. However, following the instructions exactly, I am not able to get the `SystemEvents.UserPreferencesChanged` to log a message to the Event Viewer. It also doesn't work for DisplaySettingsChanged (which is what I really want). Does this no longer work? I am running Windows 10 1909 (Build 18363), using Visual Studio 19 Version 16.6.1.

**To Reproduce**
1. Go to Example 2 outlined in the documentation for [SystemEvents](https://docs.microsoft.com/en-us/dotnet/api/microsoft.win32.systemevents?view=dotnet-plat-ext-3.1). 
2. Create the windows service as outlined in Example 2.
3. Compile, install, and run the service.
4. Open up Event Viewer, navigate to "Windows Logs"->"Application"
5. Edit your time zone
6. Refresh the Event Viewer and you should see a log entry for "TimeChanged".  This works!
7. Now edit your display background color to something different (e.g. orange)
8. Refresh the Event Viewer and you should see that NO LOG ENTRY exists for "UserPreferenceChanged".
9. Also observe that other SystemEvents, such as DisplaySettingsChanged, also do not work.

**Expected behavior**
I expected there to be an event log for UserPreferenceChanged when I edited my display background color, but no entry was logged.

**Screenshots**
Screenshot shows only TimeChanged event gets logged, no other SystemEvents are logged.
![image](https://user-images.githubusercontent.com/12551526/84524333-aa41e480-ac8e-11ea-9e2c-8634540e40a8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 1809 (Build 17763)
 - Visual Studio 2019 Version 16.6.1
 - Windows Service project created with .NET Framework 4.7.2

**Comment by KalleOlaviNiemitalo** [comment]
The SystemEvents.UserPreferenceChanged event relies on WM_SETTINGCHANGE, WM_SYSCOLORCHANGE, and WM_THEMECHANGED messages. Services do not receive these messages because of [session 0 isolation in Windows Vista and later](<https://docs.microsoft.com/windows/win32/services/service-changes-for-windows-vista> "Service Changes for Windows Vista - Win32 apps | Microsoft Docs"). Even if a service received these messages, it would not be easily able to read the new settings from the user's session.

The SystemEvents documentation already contains [a note](<https://github.com/dotnet/dotnet-api-docs/blob/c72b36ed0cc623ba2dcb0ad33ceb1b0e7aea6cbc/xml/Microsoft.Win32/SystemEvents.xml#L38-L39> "Markdown text for the Windows Vista compatibility note in the SystemEvents documentation") about that:

> Some system events might not be raised on Windows Vista. Be sure to verify that your application works as expected on Windows Vista.

Perhaps that note was written when Windows Vista was new and Windows 7 had not been released yet. Now that Windows Vista is old, the note gives the false impression that the problem applies only to Windows Vista. The problem actually applies to later versions of Windows as well.

I think the documentation would benefit from these changes:

- Change the note so it talks about services and refers to session 0 isolation. I don't think it is necessary to mention Windows Vista, because older versions of Windows are no longer supported.
- Change the example code so it does not attempt to handle the UserPreferenceChanged event in a service.

Can someone move this issue to <https://github.com/dotnet/dotnet-api-docs/issues> and make those changes?

**Comment by dwarfslava** [comment]
Does anyone knows if same is correct for SessionEnding event? Services do not receive it?

**Comment by DadOfTheDead** [comment]
Anyone got a solution for this when using .net Worker Service?
