### ISSUE TITLE
One Dollar deducted but Auth failed on sign up azure

### ISSUE THREAD

**Issue by skarmani2002** [MicrosoftDocs/feedback#289]
# Idea Title
One Dollar deducted but Auth failed on sign up azure
Be as descriptive as you can with your idea/bug report/question/suggestion.

## Issue Details
Im facing the issue on the sign up of azure cloud services .Im using UBL wiz card Pakistan  On every submit one dollar deducted but card authentication failed. 
PS : Im doing my online course on AI , Course requirement is the Microsoft azure cloud services . can you solve this problem so i can save my time and cost . Im also attaching the snap .
![screen shot 2018-04-06 at 12 47 52 pm](https://user-images.githubusercontent.com/2855261/38466562-7bd9d67e-3b44-11e8-8a2b-b6b2195f3c93.png)

Thanks

**Comment by Powerhelmsman** [comment]
@skarmani2002 Can you provide the page link of docs.microsoft.com you refer to? If this is related to product issue, you can submit the issue through https://feedback.azure.com/forums/34192--general-feedback.

**Comment by dend** [comment]
@skarmani2002 because this forum is dedicated to docs.microsoft.com feedback, we cannot help you with Azure questions.

You can refer to the following support options:

- Get answers in [Azure forums](https://azure.microsoft.com/support/forums/).
- Connect with [@AzureSupport ](https://twitter.com/AzureSupport) - answers, support, experts.
- If you have a [support plan](https://azure.microsoft.com/support/plans/), open a support request.
- Check the [status](https://status.azure.com/) of Azure.
- Search [Azure documentation](https://azure.microsoft.com/documentation).
