### ISSUE TITLE
Broken links galore (navigation from Bing search)

### ISSUE THREAD

**Issue by ElimGarak** [MicrosoftDocs/feedback#2919]
There are a lot of broken links on the site.  

**To Reproduce**
1. Search for "RAWINPUTDEVICE" on Bing.
2. Click on the link at the top that leads to https://docs.microsoft.com/en-us/windows/desktop/api/winuser/ns-winuser-tagrawinputdevice

**Expected behavior**
The documentation opens.

**Actual behavior**
You get a 404 page.

**Comment by JasonWHowell** [comment]
@EliotSeattle any idea who might be the owner of this SDK that moved?

Redirects aren't set up perhaps, since the old URL 404s. https://docs.microsoft.com/en-us/windows/desktop/api/winuser/ns-winuser-tagrawinputdevice

![image](https://user-images.githubusercontent.com/5067358/87992774-cd399280-ca9d-11ea-8d84-d2441bf67389.png)

**Comment by EliotSeattle** [comment]
The winuser.h documentation can be found here: https://docs.microsoft.com/windows/win32/api/winuser/
The API is at https://docs.microsoft.com/windows/win32/api/winuser/ns-winuser-rawinputdevice
OLD URL is docs.microsoft.com/windows/**desktop**/api/winuser/ns-winuser-tagrawinputdevice
The win32 reference content updated to a new repo a little while back. I thought they put redirects in place. 

@GrantMeStrength runs that content and can get a writer to look into this.

**Comment by GrantMeStrength** [comment]
Taking a look, thanks Eliot

**Comment by GrantMeStrength** [comment]
Looks like redirections are in place, and the search result returned links to the correct page. 
Thanks!
