### ISSUE TITLE
False positive: validation for column-header-missing

### ISSUE THREAD

**Issue by MikeRayMSFT** [MicrosoftDocs/feedback#2929]
**Describe the bug**

Validation for column-header-missing returns a false positive when the text includes a line of more than 3 options separated by a pipe (`|`). 

> Note: It appears to not trigger the false positive when there are 3 options. When there are 4 options it does trigger it. See https://github.com/MicrosoftDocs/sql-docs-pr/commit/f9fb495a85d4a505f51d36d747180fd379a236d7. 

SQL Server documentation uses pipe to represent "or" in syntax diagram segments (not code samples). 

For example, `ENCRYPTION { ON | **OFF** | SUSPEND | RESUME }   ` in line 510 of [ALTER DATABASE set options](https://docs.microsoft.com/sql/t-sql/statements/alter-database-transact-sql-set-options) on file [docs/t-sql/statements/alter-database-transact-sql-set-options.md](https://github.com/MicrosoftDocs/sql-docs-pr/blob/master/docs/t-sql/statements/alter-database-transact-sql-set-options.md)

See validation on https://github.com/MicrosoftDocs/sql-docs-pr/pull/15853

https://github.com/MicrosoftDocs/sql-docs-pr/pull/15853#issuecomment-655576947

**Expected behavior**
This is valid with our current style and is not a table.

**Comment by MightyPen** [comment]
I don't mean to interfere here in Issue #2929, but markdown provides the `\` escaping character for situations like this. I am not convinced there is any bug here other than the markdown source's lack of proper escaping.

Below is a code block containing a copy of the markdown source in question, including line "510":

- `ENCRYPTION { ON | **OFF** | SUSPEND | RESUME }`

Note that in the master .md file, this markdown source is Not in a triple-tick code block.

In my snippet code block below, just above the line 510 with the few special `|` characters, we see a proper escape of the special `<` character, as in `\<`. The same principle applies to the special characters `|`, and `\|` would fix the problem in the normal way.

- _Markdown source change, with recommended escapes added, displayed inside ticks for viewing here:_ <br/> &nbsp; `ENCRYPTION { ON \| **OFF** \| SUSPEND \| RESUME }`

- _The good rendered HTML, where the same recommended escapes are used, and no ticks are used_: <br/> &nbsp; ENCRYPTION { ON \| **OFF** \| SUSPEND \| RESUME }

---

Another less attractive option would be to enclose line 510 inside an inline pair of single tick marks, or a small set of lines inside a pair of triple ticks. However, ticks would convert the bolding `**` into plain asterisks.

---

&nbsp;

_Here is my triple-tick code block containing line 510 and its surrounding lines._

&nbsp;

```
**\<db_encryption_option> ::=**     
Controls the database encryption state.

ENCRYPTION { ON | **OFF** | SUSPEND | RESUME }     
ON     
Sets the database to be encrypted.

OFF     
Sets the database to not be encrypted.

SUSPEND     
```

Thanks. GeneMi (= MightyPen)

cc: @MikeRayMSFT @bluefooted @pmasl @CarlRabeler @rothja

**Comment by bluefooted** [comment]
You may be right @MightyPen, but this is the way all of our syntax is documented in every article that defines syntax, so if we need to escape all the pipe symbols or put code blocks around all the syntax definitions, we'll need to do a huge PR to fix all of them. I don't think any of the syntax I've edited has been escaped like this.

Regarding formatting, I don't think I like enclosing all the syntax definitions in a single code block. They're not really code, they are syntax definitions for which we have a specific style that includes braces, brackets and pipes. Those braces, brackets and pipes are not code, they are logic symbols. 

Dunno what the best way to solve this problem is, but if we can't adjust the rule, we'll need to overhaul the entire document base.

**Comment by MightyPen** [comment]
@bluefooted Hi Pam, I agree that the distinction between T-SQL **_code_** versus **_syntax_** is an important distinction.

Until recently, on markdown triple-ticks code blocks for T-SQL, the only devlang (colorizer) value that was available was `sql`. But earlier in 2020, Duncan Mackenzie created for us the new devlang `syntaxsql`. The `syntaxsql` devlang directly applies to triple-ticks code blocks that contain syntax descriptors (like `::=` etc).

We see `syntaxsql` used in hundreds of our T-SQL articles now, across two repos. The following article is just one example:
- https://docs.microsoft.com/sql/t-sql/statements/insert-transact-sql

Before `syntaxsql` became available, we had no good devlang for the T-SQL syntax code blocks. `sql` was sometimes used, and other times no devlang was specified. Neither of those options was satisfactory.

Overall, I believe that the pipe `|` problem raised by this Issue #2929 is in only a minority subset of all the T-SQL articles. FWIWorth, I believe the best course of action is to fix the perhaps 99 T-SQL articles that may have this pipe problem. These would be only a small portion of all the new Suggestion messages we need to fix in the repo 'sql-docs-pr'. And I would rather not call for the build validation rule code to be made more complicated.

We are discussing the option of obtaining vendor labor to fix Suggestion messages.

Thanks. G

**Comment by superfon** [comment]
08.07.2020 7:54 PM "Gene Milener" <notifications@github.com> napisał(a):

**Comment by MikeRayMSFT** [comment]
The rule that it's checking is for tables. 

> Column headers are required for tables. Add appropriate header text. NOTE: This Suggestion will become a Warning in late September, 2020.

The lines in question are not tables. The rule returns a positive for tables. The rule is incorrect. That should be fixed.

I do think that wrapping the lines as sqlsyntax may be necessary as well, but that's not what this rule is checking.

**Comment by bluefooted** [comment]
Thanks @MightyPen, I hadn't seen the syntaxsql code blocks, they do look nice and much more readable. I think this will still be a problem though because in many of our articles we reference the individual clauses inline with additional information in the Arguments section. We do this in the article you reference, it just doesn't happen to contain any | symbols. Perhaps we need to create an inline version of this syntaxsql? If it's only about 99 articles, that's not too bad, but would be awesome if we can get a vendor to help with that.

@MikeRayMSFT if the syntax that contains pipes is within a code block or inline code style, wouldn't the other formatting rules like this table rule be bypassed?

**Comment by MikeRayMSFT** [comment]
Yes. I have been thinking that wrapping them inline code would be helpful.

One tricky part is that in many cases the default value is presented in bold, and we can't make text bold in a code block.

**Comment by bluefooted** [comment]
Maybe we need to create an inline version of the syntaxsql style that allows for bold?

**Comment by JasonWHowell** [comment]
This is tracked internally in several places. https://ceapex.visualstudio.com/Engineering/_workitems/edit/245103

**Comment by bluefooted** [comment]
Thanks @JasonWHowell that's good to know! Also now I see that the rule only fires when there are two lines in a row with pipes without a line break in between. That should limit some of our exposure to this rule to only the top of the article where we list out the full syntax description rather than later in the article where we describe the arguments in more detail.

**Comment by JasonWHowell** [comment]
Can you all please test now. There was a deployment (as per bug https://ceapex.visualstudio.com/Engineering/_workitems/edit/245103) that should provide improvement on this validation rule.

**Comment by JasonWHowell** [comment]
#please-close
