### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by dendobi** [MicrosoftDocs/feedback#3094]
**Describe the bug**
A lot of WPF related hyperlinks are broken. Looks as if all WPF related documents cannot be reached anymore??
E.g.  [https://docs.microsoft.com/en-us/dotnet/desktop/framework/wpf/graphics-multimedia/how-to-create-a-shape-by-using-a-pathgeometry?view=netdesktop-5.0]

**To Reproduce**
Some examples:
Start by going to the folloing over view page:
[https://docs.microsoft.com/nl-nl/visualstudio/designers/getting-started-with-wpf?view=vs-2019]

Then folloing links are not working ......
[https://docs.microsoft.com/en-us/dotnet/desktop/framework/wpf/introduction-to-wpf?view=netdesktop-5.0]
[https://docs.microsoft.com/en-us/dotnet/desktop/framework/wpf/controls/index?view=netdesktop-5.0]

Very annoying.

**Comment by adegeo** [comment]
Sorry for the confusion. I caused this problem and the fix was implemented about 9 days ago. The content moved to a new folder and the redirects created were invalid, so the URLs you were being directed to had the wrong path in them. While the links you reported don't work and won't work, the pages that were linking to them will point you to the correct paths now.

Sorry again!

**Comment by JasonWHowell** [comment]
#please-close
