### ISSUE TITLE
Add Priority Queue Support in C# similar to C++

### ISSUE THREAD

**Issue by syadavcv** [MicrosoftDocs/feedback#3300]
**Describe the solution you'd like**
Please implement Heap Data structure ( priority queue in terms of C++) support in C#. It can be easily imported from C++.

**Describe alternatives you've considered**
We can use Set or other collections but that is an overkill and doing extra what we need.

**Comment by rootsmusic** [comment]
@syadavcv Where's the doc?

**Comment by svick** [comment]
.Net 6 is adding `PriorityQueue`, see [the (currently empty) doc](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.priorityqueue-2?view=net-6.0) and https://github.com/dotnet/runtime/issues/14032, the issue about adding it. Because of that (and because this is not a docs issue), I think this issue should be closed.
