### ISSUE TITLE
PDF Download produces only one page

### ISSUE THREAD

**Issue by NulAsh** [MicrosoftDocs/feedback#3348]
**Describe the bug**
I tried to download PDF for Synchapi, but downloaded PDF contains only "Overview" page

**To Reproduce**
1. Go to https://docs.microsoft.com/en-us/windows/win32/api/synchapi/
2. Click on Download PDF
3. PDF contains only "Overview" page

**Expected behavior**
PDF contains all pages from the list

**Comment by JasonWHowell** [comment]
@mcleanbyron I can't find this Win32 page at the moment. The original issue was PDF build is incomplete.

**Comment by mcleanbyron** [comment]
Unfortunately, the behavior you're seeing is expected due to the unique way that the Win32 API reference docs are built within the docs.microsoft.com platform and the way the generate PDF feature is currently implemented. However, you can generate a PDF that includes the synchapi.h API articles by creating a PDF from the [System Services](https://docs.microsoft.com/en-us/windows/win32/api/_base/) technology page that this header is associated with. Note that the resulting PDF also includes all of the APIs for other headers related to this technology area.

**Comment by mcleanbyron** [comment]
#please-close
