### ISSUE TITLE
Easy way to switch to original (English) language site

### ISSUE THREAD

**Issue by magnusseptim** [MicrosoftDocs/feedback#344]
It will be nice to give Doc readers possibility to original (English) language site

#How I see it?

Button on the right side of page whitch switch language of page (explanation in attachment) is not enough.
It just translate content of the page, but stay untouched rest of it (left side "legend" as example.)

I would like to see that this button (or the next one nearby) will allow me to see original language page.

It will be very helpfull because:
1. Quality of translation to my national language (PL) is not allways acceptable and,
2. Most of the time im reading original-language docs, and would like to do this also with Microsoft Doc fast and easy.

Thanks in advance!

![todo](https://user-images.githubusercontent.com/37555930/39567568-b2ed5aee-4ebf-11e8-84ec-049db7dcb451.png)

**Comment by dend** [comment]
@SonjaSaltzman can you please take a look?

**Comment by SonjaSaltzman** [comment]
@magnusseptim Hi, if you want to see everything in English (the content, table of contents, and the site itself), you can use the language picker at the bottom right side of the site to switch to English.  This will set a cookie on your computer so the next time it will come up in English.  Please let me know if that addresses your issue?

**Comment by mairaw** [comment]
I think it was @jdanyow that once posted a mock-up in one of the issues of a screen that would allow the user to very quickly navigate to the English version. The button was on the top nav bar. I really liked that solution. 

Given that Google will always bring their default locale as a result, we need to make it easier for customers to navigate to the English version of the site, not just the article.

**Comment by magnusseptim** [comment]
Ok,

Short story:
First of all, thanks for quick response. It is nice!
Second, @mairaw suggestion sound nice, I would like to see something like this.

A little bit longer :
At last, @SonjaSaltzman Im not sure that we think about same think. 
If we take sample MS Doc page ex : https://docs.microsoft.com/pl-pl/aspnet/core/tutorials/first-mvc-app/, at the bottom of the screen Im seeing something like this : 

![first](https://user-images.githubusercontent.com/37555930/39634710-c7a61276-4fbb-11e8-8c7a-638d22878abe.png)

After click it present us site to choose language, where we can choose it.
Ok it works, but it is wasting of time, if you ask me.
If we have button who "partialy" works (in my opinion), why we couldn't improve it?

**Comment by SonjaSaltzman** [comment]
@magnusseptim Thank you for your feedback!  Having the language picker at the bottom left of the page is a Microsoft standard, and we wanted to give customers a standard experience across all of the sites.  But I understand it is hard to find and may be cumbersome. The existing toggle for switching to English is meant for customers who want to stay in the localized site, but may not like a certain translation and want to quickly show the text in English.  It will not switch to the English site itself;  switching to the English site is only done by using the language picker (bottom left) or changing the locale in the URL (from /pl-pl/ to /en-us/).  We will need to do some more research on what is useful for most customers!
@Sara-Nicolini FYI

**Comment by magnusseptim** [comment]
Thanks for answer. I understand the reasons but will be glad if any changes had to come.

**Comment by johlju** [comment]
@SonjaSaltzman I would like to have seen, when clicking on the existing toggle for switching to English, a question "Do you always want to view pages in English?". Say yes to that will permanently change the pages to use 'en-US', or take you to a page where you can permanently change the language to your choice. One the user has permanently switched language that toggle could be changed to a link to the page were to set the permanently language.  
Since the switch exist at top of the page, it is not obvious to look at the end of the page, first I went inside my profile to see if I could switch it there. I did not find the English switch until I read this issue.

**Comment by SonjaSaltzman** [comment]
Hi @johlju thank you for the additional feedback. We have a PM assigned to solve this issue since there are several factors to take into consideration (some users prefer to see English only for machine-translated content, others never want to see English or always want to see English etc.). We will have to ask for some patience to come up with a solution that will address most if not all scenarios.  We are aiming to address this in the fall. 
cc: @bodhigautam @Sara-Nicolini
