### ISSUE TITLE
Add new D3D12 features to the "Feature support for feature levels" table on MSDN

### ISSUE THREAD

**Issue by sebmerry** [MicrosoftDocs/feedback#3827]
**Is your feature request related to a problem? Please describe.**
I'm trying to build a table of feature support caps vs feature level for reporting purposes. I'm leveraging this table on MSDN to understand what D3D features are supported/optional/etc given a feature level. The problem is that this table is incomplete, it's missing new D3D12 features like DXR, VRS, etc.

Current table: https://docs.microsoft.com/en-us/windows/win32/direct3d11/overviews-direct3d-11-devices-downlevel-intro
There is a table here with new features I'd like: https://devblogs.microsoft.com/directx/new-in-directx-feature-level-12_2/

**Describe the solution you'd like**
I'd like this table to be updated with the new features:
https://docs.microsoft.com/en-us/windows/win32/direct3d11/overviews-direct3d-11-devices-downlevel-intro

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by gewarren** [comment]
cc @stevewhims

**Comment by stevewhims** [comment]
Thanks, @sebmerry! I added the info from the blog post to the topic. The blog posts represents feature level 12_2, whereas the table in the topic represents feature levels 12_2 through 9_3. So I added extra tables rather than trying to extend the existing table.

I did notice that adding this info to the existing table makes it unreadable due to scrollbars appearing (a longstanding issue with tables in our docs). So if we do ever want to add info about these features for the other feature levels, too, then I'll need to refactor some of the columns down into the following section, and that'll be quite time-consuming.

Thanks!
-Steve
