### ISSUE TITLE
GitHub Pull Request and build bots are not setup on all repos

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/feedback#389]
**Is your feature request related to a problem? Please describe.**
Not sure if it's a staged rollout, but I noticed that PRs on https://github.com/MicrosoftDocs/vsts-docs don't have the same PR tagging, Author notification, and OpenBuild bots running as other repos

**Describe the solution you'd like**
Enable the build GitHub bots that run on https://github.com/MicrosoftDocs/visualstuio-docs on the other repos in this organization

**Describe alternatives you've considered**
These bots may be experimental, run on a particual teams resources, or are restricted for security reasons from running on other repos.

**Comment by Powerhelmsman** [comment]
@dend Do you know who is contact person for this kind of issue?

**Comment by dend** [comment]
That's by design, because the repo in question is not used for publishing to docs - it's synced upstream into a VSTS repository that is used as the de-facto publishing repo. The public-facing repository does not contain any publishing information (notice that it doesn't have any OPS configuration information).

**Comment by nschonni** [comment]
@dend fair enought 👍 
Is the plan to migrate the other repos under this org over to OpenPublishing build (eventually)?
I just appreciate the build checking when I'm doing PRs to those repose, and hope that one day that I'll be able to leverage the workflow for some of our stuff once it's opened up.
