### ISSUE TITLE
Character ^ not being displayed and causing confusion

### ISSUE THREAD

**Issue by Nakor101** [MicrosoftDocs/feedback#395]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**Link to article:**
https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2003/cc781134(v%3dws.10)

**Problem:**

Throughout the article and on other linked articles on the left, the character ^ is not being displayed.

For example on the page I linked it states:
4,294,967,295 (232 minus 1 file)
This should read:
4,294,967,295 (2^32 minus 1 file)

If you check the ntfs website it reads
http://www.ntfs.com/ntfs_vs_fat.htm
Max Files on Volume  4,294,967,295 2 ^ 32 -1

And of course if you punch that into a calculator 2^32-1 does indeed give 4,294,967,295

**Comment by Powerhelmsman** [comment]
Thanks for your elaborative feedback. unfortunately this content is no longer updating due to product lifecycle. I double check the similar article for windows server version is correct. https://docs.microsoft.com/en-us/windows-server/storage/file-server/ntfs-overview. I will close it so far. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue
