### ISSUE TITLE
redirect_url Markdown files vs. .openpublishing.redirection.json

### ISSUE THREAD

**Issue by nschonni** [MicrosoftDocs/feedback#405]
**Is your feature request related to a problem? Please describe.**
I've noticed a mix of 2 different flavours of doing redirection in the projects. sometimes the old file will be left, and replaced with
```markdown
---
redirect_url: index
---
```
And other times the redirects are done through adding entries in `.openpublishing.redirection.json`

**Describe the solution you'd like**
Probably stick to the `.openpublishing.redirection.json` since that will survive folder renames, where the Markdown metadata approach wouldn't.

**Describe alternatives you've considered**
Maybe they serve a different purpose, or produce different type of redirect.

**Comment by Powerhelmsman** [comment]
@nschonni Thanks for your suggestion. I will open a internal work item to follow up.

**Comment by Powerhelmsman** [comment]
#log-suggestion

**Comment by botcrane** [comment]
🚀 **ATTENTION**: [Internal request](https://ceapex.visualstudio.com/web/wi.aspx?pcguid=7d644393-99ad-41c8-ac53-7fa79294c720&id=23882) logged.

**Comment by meganbradley** [comment]
@nschonni this is by design. The JSON redirection file is the recommended way to maintain redirection long term, but adding the metadata in individual files is easier for authors and useful for in-progress refactoring and communication to contributors (we can add comments in the old files, as opposed to having them immediately disappear from the repo). The next Docs Authoring Pack release will contain a script for adding newly redirect articles to the JSON files and removing the Markdown files, and we are considering implementing a warning for redirected files that remain in the repo too long.

**Comment by nschonni** [comment]
@meganbradley thanks for the followup 👍 
I can understand now that the redirect is a temporary solution, and the redirect should get flagged by the authoring tools. 
Maybe it would be good to create something on the https://github.com/MicrosoftDocs/Contribute repo to underline that, or have your already filed something? I'm not sure how the MS internal processes work 😉 ❤️ ❤️ ❤️
