### ISSUE TITLE
Properly display non .sql files in SSMS solution

### ISSUE THREAD

**Issue by Crucial2K** [MicrosoftDocs/feedback#425]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Crucial2K** [comment]
Hi, as we are able to add Powershell and other scripts to an SSMS solution could these be properly formatted and colour-coded when we open them rather than as text with lots of underlines because the parser doesn't recognise words as valid SQL. Also, I like to have a Readme.sql as the first in a solution to describe what the solution is about. Could MarkDown or some other formatting technique be allowed to prettify the description rather than one big comment /* ... */? Thanks.

**Comment by Powerhelmsman** [comment]
@Crucial2K Can you provide the content page link you refer to?

**Comment by Powerhelmsman** [comment]
@Crucial2K This is a product feedback instead of docs site issue. Suggest you post you question to https://stackoverflow.com/questions/tagged/sql-server or https://feedback.azure.com/forums/908035-sql-server. I will close it now. If you have concern or question, we can reopen it and continue the discussion.
