### ISSUE TITLE
Enhance Right Side Navigation

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/feedback#446]
**Is your feature request related to a problem? Please describe.**
The Right Side navigation only shows one heading level (h3) and does not provide the ability to indent sublevels of headings. This makes it difficult to navigate through a long page.
 
**Describe the solution you'd like**
The left side navigation has indented sub levels and there should be some ability to tag the headings in multiple levels to get them to show up in the right side navigation

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/4058555/41660942-7c115de6-746b-11e8-8981-ac07509ab463.png)

**Comment by Powerhelmsman** [comment]
@ShevaDas Please confirm: we've had decision that we will not implement more granular level item in right navigation bar. Don't remember the reason. Can you help explain?

**Comment by ShevaDas** [comment]
@DeanGross thanks for the feedback! I hear you, navigating longer articles can get unwieldy. After talking this request over with our information architect, we've decided not to implement this functionality right now. It creates a near-duplicate affordance of the left-side Table of Contents, which can be confusing to users and make navigation more difficult. This also touches the content side of things—rather than adding UI components to improve navigation, we may need to instead work on creating shorter articles or better h2s.

I'm going to close this out. Thanks again for taking the time to provide feedback, and for being part of the Docs community!

**Comment by svick** [comment]
@ShevaDas 

> It creates a near-duplicate affordance of the left-side Table of Contents, which can be confusing to users and make navigation more difficult.

I think not being able to navigate to subheadings makes navigation much more difficult than some initial confusion about what the UI means.

> rather than adding UI components to improve navigation, we may need to instead work on creating shorter articles or better h2s.

I'm not sure that's always possible. For example, [the Expressions section of the C# specification](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/expressions) is produced by a 320 kB document and having subsections in the TOC would help a lot (e.g. try finding where the `new` operator is specified). But that document is the actual specification, I don't think the people who control .Net docs content have a control over it.

**Comment by ShevaDas** [comment]
@svick Understood! We'll keep that feedback in mind for the future.

**Comment by DeanGross** [comment]
ShevaDas, I'd like to respectfully disagree with your Information Architect and clarify my request. I'm not asking to duplicate the left side navigation, I'm asking to enhance/extend that navigation with some additional visual cues in the right side navigation. It would be very helpful if the right side could have 2 additional levels below the left side (maybe H3 and H4, or H4 and H5) and if the 2nd level was indented.

**Comment by mairaw** [comment]
You're right @svick, we don't have control over that. The .NET team has asked for this feature for a long time. What we suggested was that the current behavior would be the default one, but we could perhaps opt in to show more levels if the topic would benefit from that. The headings on a topic are completely different from the TOC on the left.

**Comment by DeanGross** [comment]
As a follow up, here is a very good example of why we need another level on the right side, https://docs.microsoft.com/en-us/connectors/sharepointonline/#actions, The Action and Triggers headings both have numerous subheadings, and scrolling through the page makes it very difficult to understand where you are or to get to a desired item

**Comment by ShevaDas** [comment]
@DeanGross I do agree that article is difficult to navigate. I mocked up a version that includes the h3s in the right-hand nav:

![image](https://user-images.githubusercontent.com/3937986/41796080-e9f5719e-7619-11e8-8d2d-5c185c9bf605.png)

To me, this seems more like a quick patch than a change that truly makes the article easier to navigate. So instead of adding in more sub-levels, we're actively working on a better overall browsing experience for this kind of API-esque content that attempts to address the root issues more holistically.

I did discuss adding additional levels to the side pane again with our information architect yesterday and this is not something we'll be changing. Although surfacing all levels of headers in the sidebar is compelling as a quick solution, I strongly believe in the long run it will create more problems than it solves and a poorer user experience overall.
