### ISSUE TITLE
Azure Consumption UsageDetail API keeps returning the same data

### ISSUE THREAD

**Issue by EUGinsane** [MicrosoftDocs/feedback#450]
**Describe the bug**
I am using [Azure Consumption UsageDetail](https://docs.microsoft.com/en-us/rest/api/consumption/usage%20details%20(2018-05-31)/list) API to get the VMs usage data but it seems to have problems, it keeps returning the same data (all data) even I specify filter tags.

Sample Request

> https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/providers/Microsoft.Consumption/usageDetails?$filter=tags eq 'dev:tools'&api-version=2018-05-31

My Request is the same with Sample Request
> https://management.azure.com/subscriptions/XXX/providers/Microsoft.Consumption/usageDetails?$filter=tags eq 'dev:tools'&api-version=2018-05-31

with **XXX** is my subscriptionID, I expected the result would be null because I don't have that tag value, but instead it returned all usage data.

Even with no filter request
> https://management.azure.com/subscriptions/XXX/providers/Microsoft.Consumption/usageDetails?api-version=2018-05-31

result is the same. Any solutions ? Thanks.

**Comment by hellosnow** [comment]
Update: I'm finding the right person to answer this question.

**Comment by hellosnow** [comment]
Status update: Azure consumption team is investigating.

**Comment by bgsky** [comment]
Would you test the following format in your url, and let us know if that fix the issue

/subscriptions/{subscription-id} /providers/microsoft.billing/billingperiods/20180201/providers/microsoft.consumption/usagedetails?api-version=2018-05-31&$apply=groupby((Tags))&$filter=tags eq 'dev:tools'

**Comment by Powerhelmsman** [comment]
@EUGinsane Please take a look at bgsky's response.

**Comment by ms-premp** [comment]
@EUGinsane actually groupby is not required.
/subscriptions/{subscription-id} /providers/microsoft.billing/billingperiods/20180201/providers/microsoft.consumption/usagedetails?api-version=2018-05-31&$filter=tags+eq+'dev:tools'
should work for you.
In this is not working, would you mind sharing subscription-Id which is not working.
You can raise a support ticket with these details, rather than sharing it here.

**Comment by bgsky** [comment]
@EUGinsane  Assume your subscription-id is not web direct, would you check your request again
/subscriptions/{subscription-id}/providers/microsoft.consumption/usagedetails?api-version=2018-05-31&$filter=tags+eq+'dev:tools'

From our side, we see response difference with and without tag filter. If specifying tag filter, our response only has records with those tags. Please let us know if response is not expected.

**Comment by williamBoily** [comment]
This is an old question but I am facing the same issue. I have a free trial subscription and wanted to test some requests with the tag filtering but it just does not work.

I have tried the suggested solutions above without successful results. Other `$filer` that I have tested works fine, only the tags seems problematic.

Is this issue is known or is it resolved somewhere else ?

**Comment by ms-premp** [comment]
@EUGinsane @williamBoily @bgsky I see our filtering on Tags is not generating right filter parameters and so powershell will get filtered data.
We will work on a fix.

**Comment by JorgenMaass** [comment]
Is it fixed now? 
I cant get it to work...

**Comment by keziamicro** [comment]
Hello - reviewing and cleaning up some older feedback/issues. Thanks!
