### ISSUE TITLE
Enable permanent selection for preferred language

### ISSUE THREAD

**Issue by boehle** [MicrosoftDocs/feedback#462]
# Permanent language selection

Currently it doesn't seem to be possible to select a certain language as the default language for the Microsoft Docs.
Every time I change the language using the language option at the bottom left of the page, it switches back to the language based on my location after accessing the page again, which annoying as hell.

I even tried logging in, in hopes of being able to save the default language, but didn't help.
It's really frustrating to always have to switch the language every time you access the site or to toggle the "Read this in English" button...

**Comment by boehle** [comment]
@BugsDigger ugh, that's a nice workaround :D thanks for the tip man!
Yeah and I really hope there's gonna be a real solution some time near...

**Comment by ncarandini** [comment]
Please please please do implement this request.
More over, because sometimes (very often, to be honest) it's faster and easier go to the desired MS Doc page searching from Google (or Bing if you like), every time I got a localized URL (in my case it-it) so I really would like a redirection based on my browser cookie.
As an example:
1. I search for "Xamarin forms build release app"

2. Google first suggestion is the one I like:
```
Preparazione di un'applicazione per il rilascio - Xamarin | Microsoft Docs
https://docs.microsoft.com/it-it/xamarin/android/deploy-test/release-prep/
```
please note that Google detected my country and suggested the Italian page (it-it).

3. Even if is possible to see the English content from the Italian page thanks to the EN switch (see image below), I really don't like it and I'd prefer to be automagically redirected to the en-us page.

So I do think you need to implement some sort of user settings were we can choose the preferred language.

![image](https://user-images.githubusercontent.com/139274/42932962-f18916ec-8b43-11e8-862b-72b5d57e4797.png)

**Comment by ncarandini** [comment]
An alternative way to quickly solve it is to add, next to the "Read it in English" switch, a link to the native page, like "go to English page". This is something very easy to implement.

**Comment by Powerhelmsman** [comment]
@SonjaSaltzman Can you follow up the feedback?

**Comment by SonjaSaltzman** [comment]
Looping in @bodhigautam and @Sara-Nicolini to follow up. We really appreciate the feedback.  For now, we do not have a good solution, but we are considering various approaches that may address this problem.

**Comment by bodhigautam** [comment]
Hi,
Thanks a lot for your feedback. We are working on a permanent solution to fix this issue. Till it is resolved you can follow these steps as a temporary solution.

Select the language from the language picker (one time settings)
1. Go to docs.microsoft.com
2. Scroll down to the end of the page and click on the language picker. Screenshot attached. 
![1](https://user-images.githubusercontent.com/41086513/43104838-a021ccf8-8e87-11e8-8044-3ae7dd34225c.PNG)
3. Click on the language in which you want to see the contents in future. You can always change your preference in future.
4. Close the window.

On the bing/google search:
1. If you see links which show contents other than your preferred language because of your localtion then remove the language field from the url. For eg if you see https://docs.microsoft.com/it-it/xamarin/android/deploy-test/release-prep/?tabs=vswin remove the language (for eg /it-it or /de-de) so the new link will become https://docs.microsoft.com/xamarin/android/deploy-test/release-prep/?tabs=vswin. Screenshot attached.
![3 remove language](https://user-images.githubusercontent.com/41086513/43105119-9b47001c-8e88-11e8-9359-ee01d28dc82c.PNG)
2. Go to this url and you will see the content in your preferred language (from the picker).

Note : If you open the links (without language) in a private/incognito window then you will not see the content in your preferred language as your settings are not applied there. By default it will redirect you to English page.

Hope this helps. Let us know if you face any issues. We always value your feedback.

**Comment by Powerhelmsman** [comment]
@boehle Can you verify if this resolve your issue?

**Comment by boehle** [comment]
@Powerhelmsman yeah, if I remove the lang tag it takes me to the language I specify on docs.microsoft.com.
But from google I'm still being sent to the language of my country. So it doesn't work as a global override/default.

**Comment by Powerhelmsman** [comment]
@bodhigautam Can you follow up boehle's issue?

**Comment by bodhigautam** [comment]
We are working on a permanent solution. Will update once its in place.
Thanks.

**Comment by ncarandini** [comment]
@bodhigautam: thanks for your reply but the problem with the footer page language selection is that is a preference only for URLs that not declare the language. As I said, I can click on the URL and then replace the it-it (in my case) with "en-us" but it's a tedious workaround. To just remove the "it-it" from the URLS found by Bing/Google, as you suggested, it's more painful, because I need to copy the URL, paste it somewhere, remove the language from the URL, copy and paste again on the browser (argh! :-) ).
And as described by @boehle, when clicking on a local language defined URL, the footer reset to that Language…
So at the moment I totally disregard the footer language selector (as is useless), sometime I use the "See it in English" switch and most of the time I get the Italian page, then change the language un the url and reload the page, to finally get it in English.

And I feel guilty for all the effort made to translate the English page in so many other languages!
More seriously I do think translation is important, as many developers love to read on their own language, but still we need to have a better way to set our language preferences.

I'd love to login on MS Docs as a requisite to have language preference working. I need to be signed also to comment, so it doesn't seems a big issue to me, but you have a broader picture on Docs usage, so I'm confident you're going to eventually find a good solution for this.

Thanks for your time, passion and work, Docs on GitHub and the ability to contribute really rocks!

**Comment by martencassel** [comment]
How many Swedish developers love to read about content in their native Swedish tongue ? Do you know that ? At a previous role i used to joke with my collegues and used Microsoft translated concepts during different discussions and they didn't understand a thing.

**Comment by ncarandini** [comment]
@SonjaSaltzman  why have you closed the issue?

**Comment by SonjaSaltzman** [comment]
@ncarandini reopening the issue; we don't have a clear target date for fixing this at the moment, but will try to do so by end of the year, so will keep this issue open until then.
@bodhigautam @Sara-Nicolini

**Comment by emanuel-lundman** [comment]
Please don't auto switch to machine translated docs ever. If anyone want to read machine translated docs in their own langauge then let them switch themselves. I don't know anyone who prefer reading the machine translated docs at all. People I know complains about them cause quite often they make no sense and it's infuriating having to switch back to english at the bottom of the page all the time.

**Comment by martencassel** [comment]
@emmanuel-lundman
I have never every met any IT person in my career that understand what microsoft machine translated. For fun, I've tried to talk to people about technical topics using ms machine language speak, but they have never understood me, they just laugh at me :-)

**Comment by ncarandini** [comment]
@martencassel This issue is indeed about permanent selection of preferred language! If you mean something different, please open another issue.

See the title of the issue:

### Enable permanent selection for preferred language
Currently it doesn't seem to be possible to select a certain language as the default language for the Microsoft Docs. [...]

**Comment by MCKLMT** [comment]
This feature will be very well welcomed for all non-English people playing with Microsoft technologies. I'm French and I read documentation multiple times by day. I don't count anymore the number of times I should change the language each day! It's a real pain.
Please consider increasing priority of this feature. 😉

**Comment by BugsDigger** [comment]
MCKLMT,

> I don't count anymore the number of times I should change the language each day!

consider installation of browser plugin like "Redirector". My settings are:
--------------------------------------------------
ms docs ru-ru to en-us
Redirect:	https://docs.microsoft.com/ru-ru/*
to:	https://docs.microsoft.com/en-us/$1
Example:	https://docs.microsoft.com/ru-ru/dotnet/ → https://docs.microsoft.com/en-us/dotnet/
Applies to:	Main window (address bar)
--------------------------------------------------
msdn ru-ru to en-us
Redirect:	https://msdn.microsoft.com/ru-ru/*
to:	https://msdn.microsoft.com/en-us/$1
Example:	https://msdn.microsoft.com/ru-ru/dn308572.aspx → https://msdn.microsoft.com/en-us/dn308572.aspx
Applies to:	Main window (address bar)
--------------------------------------------------

**Comment by MCKLMT** [comment]
This is a workaround but it should not be difficult to implement this feature natively. 
For Microsoft Edge, one guy has developed an interesting extension: https://www.microsoft.com/store/productId/9PN36R9NBTRM

**Comment by BugsDigger** [comment]
I agree completely but if current PITA is so big I prefer to use any workaround. :-)

**Comment by ncarandini** [comment]
@BugsDigger thanks for the workaround!

**Comment by rickardp** [comment]
Since issue #933 was set as a dup of this, I wanted to bring what I believe is the essence of that.

- If the original language (English) is *among* the list of accepted languages, never present a machine translated version.

Do this regardless of what is in the URL (or rather, fix it so that Google doesn’t take you to machine translated versions).

Machine translation is only useful as a last resort for people that can’t speak the original language.

**Comment by bodhigautam** [comment]
@rickardp Thanks a lot for the suggestion. We will add it in our backlog. Unfortunately its not in our plan right now. We will keep you updated once its picked up for development.

**Comment by srvbpigh** [comment]
Hello, @boehle
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by MCKLMT** [comment]
On the *new* Edge based on Chromium, I use this extension: https://chrome.google.com/webstore/detail/ffs-msdn-in-english/ddaknggefjjgpnlhiejepbiplceedmfl

**Comment by ncarandini** [comment]
Can I trust it? I'd much prefer a Microsoft solution, I don't trust plugins.

**Comment by srvbpigh** [comment]
Hello, @boehle
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by MCKLMT** [comment]
@CeciAc Any news on this topic?

**Comment by SonjaSaltzman** [comment]
@bodhigautam @RyanKing77 Bodhi, could you please update on the status of this feature?

**Comment by HoundThe** [comment]
Oh yes, finally found that issue exists for this insane pain in the ass, maybe atleast a basic button to turn off machine translation?

**Comment by bodhigautam** [comment]
@dendeli-msft @RyanKing77 This is for the locale redirection improvement feature we have been discussing. Can we please get it prioritized and delivered ? cc @SonjaSaltzman

**Comment by ncarandini** [comment]
Finally I've solved, using Edge Chromium (I'm actually using Beta Version 81.0.416.72 but maybe this works also un previous versions).
Going to Settings | Languages I was able to add the English language and move it to the top of the list. Now Edge use this preference and open the en-US version of Microsoft Docs web pages.
Eureka!

**Comment by Xawx** [comment]
I think every page should always open in English, not some weird stuff like `pl-pl` despite it being my native language.

Current way causes a lot of pain, which is sad, because docs are great, but having to switch to `us-us` whenever I want to read something is annoying.

Also button ""solution"" doesn't really work, because site looks like 50% is in Polish meanwhile other 50% is in English. It's more like workaround instead of a real solution. 

Also something like this:


![asd](https://user-images.githubusercontent.com/24208624/83534084-ad034380-a4f0-11ea-8955-0cca930f622a.png)


https://docs.microsoft.com/pl-pl/aspnet/core/whats-new/2020-05?view=aspnetcore-3.1

Please, English by default, always, and if somebody wants their language, then let him switch to it.

**Comment by SonjaSaltzman** [comment]
@RyanKing77 could you please update on the feature? Also, @JasonCard there is some feedback about aspnet core documentation.

**Comment by JasonCard** [comment]
Hi @Xawx 

Thank you for your feedback.
Regarding your comment that English is mixed with Polish in topic below, product names such as "ASP.NET Core", "Blazor", and "SignalR" are not localized and left in English as design: 
<https://docs.microsoft.com/pl-pl/aspnet/core/whats-new/2020-05?view=aspnetcore-3.1>

Please let me know if there was anything else that was left in English, but should have been translated.


Best regards,
Jason

**Comment by rickardp** [comment]
> Finally I've solved, using Edge Chromium (I'm actually using Beta Version 81.0.416.72 but maybe this works also on previous versions).
> Going to Settings | Languages I was able to add the English language and move it to the top of the list. Now Edge use this preference and open the en-US version of Microsoft Docs web pages.
> Eureka!

That is unfortunately not a good solution, as this will change all content on all sites to English. I am a Swedish native speaker and doing this would cause the Swedish news sites etc to present the English versions of the pages.

The solution is simple: don’t present a translated version if the original language is *anywhere* in that list. It’s as simple as that!

**Comment by HansB916** [comment]
Hi there. I would vote for a language-setting under Microsoft Docs > Profile > Settings. This feature alone would make it worth signing in, and would save me from getting unwanted knock-on effects.

**Comment by chillophil** [comment]
Another fix for "coming from Google" is to set your preferred language for Google itself. You will get search results in English, including Microsoft Docs, without having to change your browsers nor your systems "preferred default language".

If you set the language preference in a special "development" user profile of the browser, you don't even have to bother to explicitly switch back the language setting for "non-development" related searches, because for this you will have your "normal" browser user profile.

![image](https://user-images.githubusercontent.com/20392955/93503858-f4cf9e80-f918-11ea-9716-0dab0c30e2b8.png)

**Comment by keziamicro** [comment]
Hello - reviewing and cleaning up some older feedback/issues. Thanks!

**Comment by Phenek** [comment]
It will be nice if Microsoft docs could save the switch state (read in english) in cookies

**Comment by SonjaSaltzman** [comment]
Hi @Khairunj - I think this falls into your ownership area now.

**Comment by hansmbakker** [comment]
@keziamicro it seems you closed this while it is not fixed. The automatic translations are subpar (root cause) and having to click "read in English" everytime is tiresome...

#please-reopen

**Comment by danielnachtrub** [comment]
UX would benefit from this. It's somehow annoying when searching in english on google and being redirected to a localized page afterwards.

**Comment by aWeinzierl** [comment]
> Hello - reviewing and cleaning up some older feedback/issues. Thanks!

please review this issue more thoroughly

**Comment by marta-beznos** [comment]
Is there any permanent solution for this issue?

Let alone that this is not very convenient to get the page in the local language when you're searching in English, more annoying is when the language you get is not even the language of your country.
Is there a possibility not to get russian language for searches from Ukraine? It's especially painful now at the time of war that russia started against our country. 
I have changed every possible setting in google to make sure russian doesn't appear anywhere there and switched off automatic language suggestion. Now I don't get results in russian anywhere except Microsoft Docs web site. I'm a .Net Developer, so I read a lot of Microsoft docs and do those searches every day and this is something that really bothers me a lot.
Hope for understanding and advice.
