### ISSUE TITLE
allow complex searches using "and" and "or"

### ISSUE THREAD

**Issue by supernova-eng** [MicrosoftDocs/feedback#51]
Trying to find articles which tackle a combination of words is a nightmare here. Trying to find articles which tell me how to dock a window in Visual Studio, I want a combination of "dock" "AND "window" AND "Visual studio". Put even the first two into the search string and you get every single article which has any of these words. 

Or is there some refined search engine hiding somewhere?

----------
⚠ Idea migrated from UserVoice

**Created By:** PeterT
**Created On:** 2017/12/18 12:34:43 +0000
**Votes at Migration:** 3
**Supporters at Migration:** 3

**Comment by presleyy** [comment]
The articles having any of these words will be returned, but search engine does have the logic to rank them by similarity from the search query. So an article having all these words "dock", "window", "visual", and "studio" will definitely be at better position comparing to others just having one or two words matched. Searching in Docs entire documents can be the main reason in this case because there have some many articles having all these words. Suggest searching in "VS IDE" scope, which will return much better results. On the other hand, we have a feature work item (planning phase) of adding filters with facets in search results, which later will help on this scenario.

**Comment by Powerhelmsman** [comment]
@log-suggestion @presleyy

**Comment by presleyy** [comment]
Site search does consider both "and" and "or" when looking for relevant content. What can help the scenario here is to have a search scope like "VS IDE" - which could return more relevant results. Currently we don't allow users to change the scope or filter by product/service scope. We have the [feature](https://ceapex.visualstudio.com/Engineering/_workitems/edit/25952) in planning phase about this.

**Comment by keziamicro** [comment]
Hello - reviewing and cleaning up some older feedback/issues. Thanks!
