### ISSUE TITLE
Azure SQL Quickstart doc 404 link error

### ISSUE THREAD

**Issue by hntddt123** [MicrosoftDocs/feedback#547]
**Link to article:**
<img width="440" alt="2018-07-23 16 27 37" src="https://user-images.githubusercontent.com/4081929/43104912-a4cde2e4-8e98-11e8-951b-64bc82da4256.png">
https://go.microsoft.com/fwlink/?LinkID=394042

**Problem:**
"Selecting the appropriate database collation for your app" link broken under quickstart tab

**Created by:** Nientai Ho 
**Date:** 7/23/2018

**Comment by Powerhelmsman** [comment]
@hntddt123 Can you provide the Docs site page link including the broken link?

**Comment by hntddt123** [comment]
It's on Azure Dashboard->quickstart
This is mine link don't know if works on public
https://portal.azure.com/#@UofH.UH.EDU/resource/subscriptions/aadf75d4-e0a3-48c5-bf40-5076ae355e2c/resourceGroups/appData/providers/Microsoft.Sql/servers/repairreport/databases/RepairReportDataBase/quickStart

**Comment by Powerhelmsman** [comment]
@hntddt123 I don't have access to your link. This channel is about Docs.microsoft.com instead of product feedback. Can you submit your question to https://azure.microsoft.com/en-us/support/community/ . I will close this issue so far. We can reopen the issue if you have other question related to this.
