### ISSUE TITLE
Azure REST API and Templates browsers should use same left-nav hierarchy

### ISSUE THREAD

**Issue by jtuliani** [MicrosoftDocs/feedback#557]
**Is your feature request related to a problem? Please describe.**
Compare:
Azure template reference: https://docs.microsoft.com/azure/templates/
Azure REST API reference: https://docs.microsoft.com/rest/api/?view=Azure

Why is the left-nav hierarchy different? The template reference is strictly organized by resource provider. The REST API reference is organized by...well, I don't know what it is, frankly. Networking is split up with DNS and Traffic Manager separate, but a bunch of other top-level resource types grouped under 'virtual networks' (which is itself a resource type)

**Describe the solution you'd like**
Use the resource-provider hierarchy (as used on the template reference) on the REST API reference.

**Describe alternatives you've considered**
Nothing else makes any sense.

**Additional context**
Thanks for listening!

**Comment by dend** [comment]
@mikekinsman could you help address this with the content partners?

**Comment by mikekinsman** [comment]
@jtuliani whoa *very* late reply here.  I missed the ping back in July and I didn't come back around to it.  My apologies for the huge delay.   The accurate, but incomplete answer to your question, is that the two TOCs are maintained and built separately, which is why they deviate.  We automatically generate the REST content, which makes it much faster, but introduces some constraints on how the content is structured.  Going forward I think @rloutlaw and @dend might be able comment on the future of reference content structure from Azure.  Thanks for your feedback on how consistency for reference content across Azure is important for your usage of content.
