### ISSUE TITLE
MethodInfo.Invoke

### ISSUE THREAD

**Issue by mairaw** [MicrosoftDocs/feedback#579]
Original issue https://github.com/dotnet/docs/issues/6822 from @NetMage

MethodInfo.Invoke link under Methods in Tree goes to .Net 1.1 page instead of MethodBase.Invoke page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc2c5677-4ada-334c-6fe1-13329ed66839
* Version Independent ID: 33eda1ff-e736-e2f4-a44b-14f3da3d7a7b
* Content: [MethodInfo Class (System.Reflection)](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.methodinfo?view=netframework-4.7.1)
* Content Source: [xml/System.Reflection/MethodInfo.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Reflection/MethodInfo.xml)
* Product: **dotnet-api**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by mairaw** [comment]
I could repro this., It happens when you click on the TOC link that takes you to https://docs.microsoft.com/en-us/dotnet/api/system.reflection.methodinfo.invoke?view=netframework-1.1 

![image](https://user-images.githubusercontent.com/12971179/43663625-0ec79472-971f-11e8-9921-7b9068c7e9a0.png)

**Comment by Powerhelmsman** [comment]
@dend Is this your area?

**Comment by dend** [comment]
@mairaw is the method available in the newer versions of .NET Framework?

**Comment by mairaw** [comment]
It's inherited from the parent class in newer versions @dend

**Comment by dend** [comment]
@mairaw actually, I see [this](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.memberinfo.system-runtime-interopservices-_memberinfo-invoke?view=netframework-4.7.2#System_Reflection_MemberInfo_System_Runtime_InteropServices__MemberInfo_Invoke_System_UInt32_System_Guid__System_UInt32_System_Int16_System_IntPtr_System_IntPtr_System_IntPtr_System_IntPtr_) - the bug is likely to do with the TOC versioning. Tracked [here](https://ceapex.visualstudio.com/Engineering/_workitems/edit/31482).

**Comment by dend** [comment]
This is duplicate of #347 and is tracked with the bug above, so closing this item 😄

**Comment by mairaw** [comment]
Do you also have a duplicate label @dend? Easier to see when scanning issues.

**Comment by rpetrusha** [comment]
I'm wondering if this issue should be reopened, @dend. It doesn't seem like it's a strict duplicate of #374.

The problem here is twofold:
- The member list in the documentation for the MethodInfo type does not correctly list all members. It completely excludes the following members:
   - ContainsGenericParameters (inherited from MethodBase)
   - IsGenericMethod (inherited from MethodBase)
   - IsGenericMethodDefinition (inherited from MethodBase)
   - GetType (inherited from MethodBase)
   - Invoke(Object, Object[]) (inherited from MethodBase)
- The MethodBase TOC includes these members. However, selecting them links to the 3.5 version of the documentation.
 
The reason is that, in .NET Framework 1.1 through 3.5, MethodInfo provided an implementation of these methods. However, the implementations were identical to the base class MethodBase implementations, so in .NET Framework 4, the MethodInfo implementation was removed.

**Comment by mairaw** [comment]
Can we reopen tgus @Powerhelmsman @dend based on @rpetrusha's feedback?

**Comment by docs-product** [comment]
Assigning to @mimisasouvanh as the PM driving the .NET experience.

**Comment by mairaw** [comment]
I don't see Invoke listed under later versions anymore, so closing this.
