### ISSUE TITLE
Dynamics CRM 365 v8.2 Links are being redirected to v9.0 references

### ISSUE THREAD

**Issue by kschepperly** [MicrosoftDocs/feedback#596]
All the reference links for Dynamics CRM v.8.0-8.2 are now being redirected to v9.0 which is completely different than 8.X. I urgently need to access the Client API Object Model references, mainly the Xrm.Page Object Model. This is the previous link I used:
https://msdn.microsoft.com/en-us/library/gg328255.aspx

which now redirects here:
https://docs.microsoft.com/en-us/dynamics365/customer-engagement/developer/programming-reference

**Comment by dend** [comment]
@jmazzotta @Khairunj can you please take a look at this issue?

**Comment by Khairunj** [comment]
https://github.com/kschepperly  : sorry for the issue you faced we have restored the reference content on MSDN and once ready we will move them to previous versions with redirect in place.  Please bookmark the pages on MSDN so that you can find them with redirect.  The content on previous version site https://docs.microsoft.com/en-us/previous-versions/  will not be indexed.

**Comment by Khairunj** [comment]
The issue described here is now fixed.
