### ISSUE TITLE
Broken link in DevTest Labs docs

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#6]
In the DevTest Labs docs page (https://docs.microsoft.com/en-us/azure/devtest-lab/), the link to 'Get Started creating VM artifacts with Azure DevTest Labs' is broken (leads to a 404)

----------
⚠ Idea migrated from UserVoice

**Created By:** Anonymous
**Created On:** 2018/03/02 18:18:19 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by dend** [comment]
This is a content issue, so will be closed soon. @erickson-doug @TomArcher - someone on your team can help address this?

**Comment by TomArcher** [comment]
@craigcaseyMSFT Could you take a look at this when you get a minute?

**Comment by craigcaseyMSFT** [comment]
@TomArcher  I've got this fixed and in a PR waiting for merge. I'll comment back here when it is published.

**Comment by dend** [comment]
@TomArcher @craigcaseyMSFT any updates here?

**Comment by craigcaseyMSFT** [comment]
@dend  -  This was fixed at one point, but since then, that team has reorged all of the DTL content. In fact, looks like the link in your original comment (https://docs.microsoft.com/en-us/azure/devtest-lab/) returns a 404 now as well.

Unfortunately, I no longer work on DTL. Please contact Ji Eun Kwon to help resolve this issue. Thanks.

**Comment by Powerhelmsman** [comment]
This issue is transferred to content team so they can fix it ASAP.
