### ISSUE TITLE
The "Start Turtorial" link on iOS Development Center, doesn't.

### ISSUE THREAD

**Issue by GrantMeStrength** [MicrosoftDocs/feedback#612]
https://azure.microsoft.com/en-us/develop/mobile/ios/

On this page, the first and largest button is one that says "Start Tutorial", but it goes to a VERY busy page with no obvious next step to find the iOS tutorial.

**Comment by Powerhelmsman** [comment]
@GrantMeStrength Thanks for your feedback. It looks like your concern is about azure.microsoft.com instead of Docs.microsoft.com. So I transferred you suggestion to Azure.com feedback channel. https://feedback.azure.com/forums/34192--general-feedback/suggestions/35135659-the-start-turtorial-link-on-ios-development-cent You can track the status there.

**Comment by GrantMeStrength** [comment]
Thanks!
