### ISSUE TITLE
Implement a signal/R hub that I can connect to giving me a ping when keywords of interest appear

### ISSUE THREAD

**Issue by botcrane** [MicrosoftDocs/feedback#69]
I would like to have a Signal/R hub or some other way to get a signal when new keywords of interest appear. I'd like to hook up a RP2 on IoT Core to it and give a green light when it's time to go online and have a look :)

----------
⚠ Idea migrated from UserVoice

**Created By:** Joost van Schaik
**Created On:** 2017/12/08 12:54:38 +0000
**Votes at Migration:** 1
**Supporters at Migration:** 1

**Comment by Powerhelmsman** [comment]
@dend Our team blog site can resolve the request, right? But our blog site don't have a way to allow user to subscribe

**Comment by dend** [comment]
@LocalJoost can you please add more info about the request? What keywords of interest did you have in mind?

**Comment by LocalJoost** [comment]
Honestly, it's so long ago I created this I don't remember. I think it was just a funny idea to leverage IoT back then. Just forget about it

**Comment by Powerhelmsman** [comment]
@LocalJoost Thanks for your feedback. This issue was migrated from user voice. I don't know your GitHub profile ID so can't ping you to clarify the issue early. Sorry for late follow up. I have to close this issue so far due to no enough information to proceed. Welcome to provide new feedback in the future.
