### ISSUE TITLE
Release Pipeline Variable Sorting

### ISSUE THREAD

**Issue by shortcircuit21** [MicrosoftDocs/feedback#706]
In the release pipeline variables, there are options to filter by scope (example dev, test, and prod) or use a grid view to see each variable by scope. In the list view there isn't a way to sort by column header.

I'd like to be able to click on scope and see a sorted list of each scope grouped.

I've began to use the grid view, but it's a bit hard to use if you have more than three scopes including Release. You have to start horizontally scrolling and you lose the name column. I've tried to use the filter, but at times when I need to see everything there isn't a clear and concise way of doing this by scope.

**Comment by shortcircuit21** [comment]
It's any Release Pipeline created. Under the release pipeline you have a
variable tab that has Key value scope columns. I can't link a specific page
because you wouldn't be able to get to it due to access permissions.

**Comment by Powerhelmsman** [comment]
@shortcircuit21 Can't identify where is issue without more information. The channel is for Docs site issue or content issue. Your issue is more like product feedback. So can you go to specific product page to raise the feedback? I will close it here. But we can definitely reopen it if we have more information.
