### ISSUE TITLE
Cannot sign in to Power Apps development sites / apps without organizational account

### ISSUE THREAD

**Issue by hansmbakker** [MicrosoftDocs/feedback#728]
Microsoft Learn has a section about PowerApps. They require an organizational account, and that account may not be blocked for PowerApps (apparently some organizations block it).

This is not listed in the prerequisites, and there is no way to do the exercises without such an account. A sandbox environment would be nice if you do not have such an account (like the Azure trainings have)

**Comment by Powerhelmsman** [comment]
@hansmbakker Thanks for your feedback. On the bottom of each Microsoft Learn unit, there is a channel to report an issue. I've already helped you create this one. 

![image](https://user-images.githubusercontent.com/33136632/46494979-0e798900-c7c9-11e8-89ad-ea94dcd7d03c.png)

The following message is from "report an issue": 
Note: While we are not directly responding to all customers at this time, please know that we are reviewing any and all feedback that is coming in. 

I will close this issue here. If you have any concern, other stuff related to this issue. We can reopen it. I promise I will @ you if I get the response from the team.

**Comment by hansmbakker** [comment]
Thank you! I didn't see that section, I must've overlooked it.
