### ISSUE TITLE
Content of webpage doesn't look properly

### ISSUE THREAD

**Issue by HaDayaGo** [MicrosoftDocs/feedback#815]
The content of _Windows UWP overview_ webpage doesn't look properly in maximized browser window, some horizontal content of webpage is out of browsing area even webpage doesn't show horizontal scrolling bar to access that content.

**Link of  Page**
https://docs.microsoft.com/en-us/windows/uwp/get-started/

Make them look properly even in maximized browser window.

**Maximized Browser window**
![screenshot 4](https://user-images.githubusercontent.com/19414508/47721117-72cb2380-dc75-11e8-9184-27b9cb3adb1f.png)

![screenshot 6](https://user-images.githubusercontent.com/19414508/47722564-afe4e500-dc78-11e8-8d10-03deae0e2334.png)

 - OS: Windows version 1809 (17763)
 - Browser: Edge, Opera

**Comment by Powerhelmsman** [comment]
@HaDayaGo I create a internal bug to track it. https://icm.ad.msft.net/imp/v3/incidents/details/89940377/home

**Comment by Powerhelmsman** [comment]
@QuinnRadich Can you take a look at this bug?

**Comment by QuinnRadich** [comment]
Apologies for the delayed response to this issue. I believe this issue was always tied to larger site engineering and architecture settings on docs.microsoft.com, and wasn't related to the page in question. I've gone through and checked the page as it stands now, and I haven't been able to reproduce this issue.

If this is still noticeable now after all this time, I'd encourage you to submit a new issue stating as such, and I'll check again and inquire with our docs platform engineering team. Thank you.
