### ISSUE TITLE
Incorrect info at direct3dhlsl/dx-graphics-hlsl-pow

### ISSUE THREAD

**Issue by pkristof** [MicrosoftDocs/feedback#997]
**🛑 IMPORTANT**: You can get your feedback addressed faster if you **use the comment section for the article in which you encountered a problem**.

**https://docs.microsoft.com/en-us/windows/desktop/direct3dhlsl/dx-graphics-hlsl-pow**
Table in the remarks section should state "1/x^y" instead of "1/x^-y" for row "x > 0, y < 0".

**Comment by Powerhelmsman** [comment]
@ginami Can you take a look at this issue?

**Comment by ginami** [comment]
Hello @pkristof -- thank you for letting us know! We'll get the page updated.

**Comment by stevewhims** [comment]
Hi, @pkristof, the topic is actually correct. If you take x^-2 and apply to that what it says in the topic (which is 1//x^-y, then you get 1/x^-(-2)), or 1/x^2. Which is correct. x is x and y is -2. So, minus -2 is 2. If I changed the topic as suggested, then the outcome would be 1/x^-2, which is incorrect.

This issue is ready to close, if you agree.

Thanks! ~Steve
